#!/usr/bin/python
# encoding:utf-8

# @author:xilin.zheng

# @file:mid.py.py

# @time:2018/11/16 下午4:45
from config import output_sample_data_path_pre,output_feature_path_pre,dropFrame
from pyspark import SparkContext
from pyspark.sql import HiveContext
import sys
import re
import time

reload(sys)
sys.setdefaultencoding('utf-8')

key_cal = 'avg'
print key_cal + "_sql_daily" + " run " + str(time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()))  +  "*"*90



sc = SparkContext(appName= key_cal + "_sql_daily")
hsqlContext = HiveContext(sc)

input_path = sys.argv[1]
output_path =  input_path.replace('.csv', '').replace('/*', '')

match_sample_data_path = output_sample_data_path_pre + output_path 


matchRDDS = sc.textFile(match_sample_data_path)
#midRDDS = sc.textFile('/Users/xilin.zheng/yeepay/PRD5/sql/personal_cfsl_loan_deduct_seq_100000/*')
matchRDD = matchRDDS.map(lambda x: x.split(',')).map(lambda row: (
    row[0], row[1], row[2], row[3], row[4], row[5], row[6], row[7], row[8], row[9], row[10], row[11], row[12]))
midDf = hsqlContext.createDataFrame(matchRDD,
                                    ['id_pay', 'idcard', 'no_card', 'no_mec', 'mec_type', 'repay_tm', 'pay_result',
                                     'amt', 'flag_error', 'month', 'day', 'amt_s', 'recall_date'])

hsqlContext.registerDataFrameAsTable(midDf, "personal_cfsl_loan_deduct_seq")


midsqlDf = hsqlContext.sql("select aa.idcard,"
                           "aa.recall_date,"
                           "mec_type as goods_if_subbizcatname,"
                           "case when flag_error = 1 then 1 when flag_error > 1 then 2 else 3 end as req_if_trademsg,"
                           "pay_result as pay_result,"
                           "amt as amt,"
                           "datediff(aa.recall_date, first_value(repay_tm) over(partition by no_mec,aa.idcard,aa.recall_date order by repay_tm)) as day_open,"
                           "datediff(aa.recall_date, repay_tm) as day_pay,"
                           "row_number() over (partition by aa.idcard,aa.recall_date order by repay_tm desc ) as row_num "
                           "from personal_cfsl_loan_deduct_seq aa ")


hsqlContext.registerDataFrameAsTable(midsqlDf, "personal_cfsl_loan_deduct_seq_mid")

avgMidDf = hsqlContext.sql("select idcard,"
                           "recall_date,"
                           "goods_if_subbizcatname,"
                           "req_if_trademsg,"
                           "pay_result,"
                           "case when day_open <= 1 then 1 when day_open <= 7 then 2 when day_open <= 14 then 3 when day_open <= 21 then 4 when day_open <= 30 then 5 when day_open <= 90 then 6 when day_open <= 180 then 7 when day_open <= 360 then 8 else 9 end as day_open,"
                           "case when day_pay <= 1 then 1 when day_pay <= 7 then 2 when day_pay <= 14 then 3 when day_pay <= 21 then 4 when day_pay <= 30 then 5 when day_pay <= 90 then 6 when day_pay <= 180 then 7 when day_pay <= 360 then 8 else 9 end as day_pay,"
                           "case when row_num <= 5 then 1 when row_num <= 20 then 2 when row_num <= 50 then 3 when row_num <= 100 then 4 else 5 end as row_num,"
                           "sum(amt) as amt,"
                           "count(*) as count_num "
                           "from personal_cfsl_loan_deduct_seq_mid yy "
                           "group by idcard,"
                           "recall_date,"
                           "goods_if_subbizcatname,"
                           "req_if_trademsg,"
                           "pay_result,"
                           "case when day_open <= 1 then 1 when day_open <= 7 then 2 when day_open <= 14 then 3 when day_open <= 21 then 4 when day_open <= 30 then 5 when day_open <= 90 then 6 when day_open <= 180 then 7 when day_open <= 360 then 8 else 9 end,"
                           "case when day_pay <= 1 then 1 when day_pay <= 7 then 2 when day_pay <= 14 then 3 when day_pay <= 21 then 4 when day_pay <= 30 then 5 when day_pay <= 90 then 6 when day_pay <= 180 then 7 when day_pay <= 360 then 8 else 9 end,"
                           "case when row_num <= 5 then 1 when row_num <= 20 then 2 when row_num <= 50 then 3 when row_num <= 100 then 4 else 5 end")

hsqlContext.registerDataFrameAsTable(avgMidDf, "personal_cfsl_loan_deduct_seq_avg_mid")

avgsqlDf = hsqlContext.sql("select idcard,recall_date,"
                           "round(sum(case when day_pay<=1 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=1 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adazaa,"
                           "round(sum(case when day_pay<=1 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_pay<=1 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adazab,"
                           "round(sum(case when day_pay<=1 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when day_pay<=1 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adazac,"
                           "round(sum(case when day_pay<=1 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when day_pay<=1 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adazaz,"
                           "round(sum(case when day_pay<=1 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=1 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adazba,"
                           "round(sum(case when day_pay<=1 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_pay<=1 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adazbb,"
                           "round(sum(case when day_pay<=1 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when day_pay<=1 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adazbc,"
                           "round(sum(case when day_pay<=1 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when day_pay<=1 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adazbz,"
                           "round(sum(case when day_pay<=1 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=1 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adazza,"
                           "round(sum(case when day_pay<=1 and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_pay<=1 and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adazzb,"
                           "round(sum(case when day_pay<=1 and pay_result =1 then amt else 0 end)/sum(case when day_pay<=1 and pay_result =1 then count_num else 0 end), 2) as t01adazzc,"
                           "round(sum(case when day_pay<=1 then amt else 0 end)/sum(case when day_pay<=1 then count_num else 0 end), 2) as t01adazzz,"
                           "round(sum(case when day_pay<=2 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=2 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adbzaa,"
                           "round(sum(case when day_pay<=2 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_pay<=2 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adbzab,"
                           "round(sum(case when day_pay<=2 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when day_pay<=2 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adbzac,"
                           "round(sum(case when day_pay<=2 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when day_pay<=2 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adbzaz,"
                           "round(sum(case when day_pay<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adbzba,"
                           "round(sum(case when day_pay<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_pay<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adbzbb,"
                           "round(sum(case when day_pay<=2 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when day_pay<=2 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adbzbc,"
                           "round(sum(case when day_pay<=2 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when day_pay<=2 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adbzbz,"
                           "round(sum(case when day_pay<=2 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=2 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adbzza,"
                           "round(sum(case when day_pay<=2 and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_pay<=2 and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adbzzb,"
                           "round(sum(case when day_pay<=2 and pay_result =1 then amt else 0 end)/sum(case when day_pay<=2 and pay_result =1 then count_num else 0 end), 2) as t01adbzzc,"
                           "round(sum(case when day_pay<=2 then amt else 0 end)/sum(case when day_pay<=2 then count_num else 0 end), 2) as t01adbzzz,"
                           "round(sum(case when day_pay<=3 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=3 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adczaa,"
                           "round(sum(case when day_pay<=3 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_pay<=3 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adczab,"
                           "round(sum(case when day_pay<=3 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when day_pay<=3 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adczac,"
                           "round(sum(case when day_pay<=3 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when day_pay<=3 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adczaz,"
                           "round(sum(case when day_pay<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adczba,"
                           "round(sum(case when day_pay<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_pay<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adczbb,"
                           "round(sum(case when day_pay<=3 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when day_pay<=3 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adczbc,"
                           "round(sum(case when day_pay<=3 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when day_pay<=3 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adczbz,"
                           "round(sum(case when day_pay<=3 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=3 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adczza,"
                           "round(sum(case when day_pay<=3 and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_pay<=3 and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adczzb,"
                           "round(sum(case when day_pay<=3 and pay_result =1 then amt else 0 end)/sum(case when day_pay<=3 and pay_result =1 then count_num else 0 end), 2) as t01adczzc,"
                           "round(sum(case when day_pay<=3 then amt else 0 end)/sum(case when day_pay<=3 then count_num else 0 end), 2) as t01adczzz,"
                           "round(sum(case when day_pay<=4 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=4 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01addzaa,"
                           "round(sum(case when day_pay<=4 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_pay<=4 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01addzab,"
                           "round(sum(case when day_pay<=4 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when day_pay<=4 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01addzac,"
                           "round(sum(case when day_pay<=4 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when day_pay<=4 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01addzaz,"
                           "round(sum(case when day_pay<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01addzba,"
                           "round(sum(case when day_pay<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_pay<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01addzbb,"
                           "round(sum(case when day_pay<=4 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when day_pay<=4 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01addzbc,"
                           "round(sum(case when day_pay<=4 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when day_pay<=4 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01addzbz,"
                           "round(sum(case when day_pay<=4 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=4 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01addzza,"
                           "round(sum(case when day_pay<=4 and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_pay<=4 and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01addzzb,"
                           "round(sum(case when day_pay<=4 and pay_result =1 then amt else 0 end)/sum(case when day_pay<=4 and pay_result =1 then count_num else 0 end), 2) as t01addzzc,"
                           "round(sum(case when day_pay<=4 then amt else 0 end)/sum(case when day_pay<=4 then count_num else 0 end), 2) as t01addzzz,"
                           "round(sum(case when day_pay<=5 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=5 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adezaa,"
                           "round(sum(case when day_pay<=5 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_pay<=5 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adezab,"
                           "round(sum(case when day_pay<=5 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when day_pay<=5 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adezac,"
                           "round(sum(case when day_pay<=5 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when day_pay<=5 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adezaz,"
                           "round(sum(case when day_pay<=5 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=5 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adezba,"
                           "round(sum(case when day_pay<=5 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_pay<=5 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adezbb,"
                           "round(sum(case when day_pay<=5 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when day_pay<=5 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adezbc,"
                           "round(sum(case when day_pay<=5 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when day_pay<=5 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adezbz,"
                           "round(sum(case when day_pay<=5 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=5 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adezza,"
                           "round(sum(case when day_pay<=5 and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_pay<=5 and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adezzb,"
                           "round(sum(case when day_pay<=5 and pay_result =1 then amt else 0 end)/sum(case when day_pay<=5 and pay_result =1 then count_num else 0 end), 2) as t01adezzc,"
                           "round(sum(case when day_pay<=5 then amt else 0 end)/sum(case when day_pay<=5 then count_num else 0 end), 2) as t01adezzz,"
                           "round(sum(case when day_pay<=6 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=6 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adfzaa,"
                           "round(sum(case when day_pay<=6 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_pay<=6 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adfzab,"
                           "round(sum(case when day_pay<=6 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when day_pay<=6 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adfzac,"
                           "round(sum(case when day_pay<=6 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when day_pay<=6 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adfzaz,"
                           "round(sum(case when day_pay<=6 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=6 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adfzba,"
                           "round(sum(case when day_pay<=6 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_pay<=6 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adfzbb,"
                           "round(sum(case when day_pay<=6 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when day_pay<=6 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adfzbc,"
                           "round(sum(case when day_pay<=6 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when day_pay<=6 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adfzbz,"
                           "round(sum(case when day_pay<=6 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=6 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adfzza,"
                           "round(sum(case when day_pay<=6 and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_pay<=6 and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adfzzb,"
                           "round(sum(case when day_pay<=6 and pay_result =1 then amt else 0 end)/sum(case when day_pay<=6 and pay_result =1 then count_num else 0 end), 2) as t01adfzzc,"
                           "round(sum(case when day_pay<=6 then amt else 0 end)/sum(case when day_pay<=6 then count_num else 0 end), 2) as t01adfzzz,"
                           "round(sum(case when day_pay<=7 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=7 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adgzaa,"
                           "round(sum(case when day_pay<=7 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_pay<=7 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adgzab,"
                           "round(sum(case when day_pay<=7 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when day_pay<=7 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adgzac,"
                           "round(sum(case when day_pay<=7 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when day_pay<=7 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adgzaz,"
                           "round(sum(case when day_pay<=7 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=7 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adgzba,"
                           "round(sum(case when day_pay<=7 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_pay<=7 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adgzbb,"
                           "round(sum(case when day_pay<=7 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when day_pay<=7 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adgzbc,"
                           "round(sum(case when day_pay<=7 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when day_pay<=7 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adgzbz,"
                           "round(sum(case when day_pay<=7 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=7 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adgzza,"
                           "round(sum(case when day_pay<=7 and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_pay<=7 and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adgzzb,"
                           "round(sum(case when day_pay<=7 and pay_result =1 then amt else 0 end)/sum(case when day_pay<=7 and pay_result =1 then count_num else 0 end), 2) as t01adgzzc,"
                           "round(sum(case when day_pay<=7 then amt else 0 end)/sum(case when day_pay<=7 then count_num else 0 end), 2) as t01adgzzz,"
                           "round(sum(case when day_pay<=8 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=8 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adhzaa,"
                           "round(sum(case when day_pay<=8 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_pay<=8 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adhzab,"
                           "round(sum(case when day_pay<=8 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when day_pay<=8 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adhzac,"
                           "round(sum(case when day_pay<=8 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when day_pay<=8 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adhzaz,"
                           "round(sum(case when day_pay<=8 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=8 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adhzba,"
                           "round(sum(case when day_pay<=8 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_pay<=8 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adhzbb,"
                           "round(sum(case when day_pay<=8 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when day_pay<=8 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adhzbc,"
                           "round(sum(case when day_pay<=8 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when day_pay<=8 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adhzbz,"
                           "round(sum(case when day_pay<=8 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=8 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adhzza,"
                           "round(sum(case when day_pay<=8 and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_pay<=8 and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adhzzb,"
                           "round(sum(case when day_pay<=8 and pay_result =1 then amt else 0 end)/sum(case when day_pay<=8 and pay_result =1 then count_num else 0 end), 2) as t01adhzzc,"
                           "round(sum(case when day_pay<=8 then amt else 0 end)/sum(case when day_pay<=8 then count_num else 0 end), 2) as t01adhzzz,"
                           "round(sum(case when row_num<=1 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when row_num<=1 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adizaa,"
                           "round(sum(case when row_num<=1 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when row_num<=1 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adizab,"
                           "round(sum(case when row_num<=1 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when row_num<=1 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adizac,"
                           "round(sum(case when row_num<=1 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when row_num<=1 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adizaz,"
                           "round(sum(case when row_num<=1 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when row_num<=1 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adizba,"
                           "round(sum(case when row_num<=1 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when row_num<=1 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adizbb,"
                           "round(sum(case when row_num<=1 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when row_num<=1 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adizbc,"
                           "round(sum(case when row_num<=1 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when row_num<=1 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adizbz,"
                           "round(sum(case when row_num<=1 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when row_num<=1 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adizza,"
                           "round(sum(case when row_num<=1 and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when row_num<=1 and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adizzb,"
                           "round(sum(case when row_num<=1 and pay_result =1 then amt else 0 end)/sum(case when row_num<=1 and pay_result =1 then count_num else 0 end), 2) as t01adizzc,"
                           "round(sum(case when row_num<=1 then amt else 0 end)/sum(case when row_num<=1 then count_num else 0 end), 2) as t01adizzz,"
                           "round(sum(case when row_num<=2 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when row_num<=2 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adjzaa,"
                           "round(sum(case when row_num<=2 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when row_num<=2 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adjzab,"
                           "round(sum(case when row_num<=2 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when row_num<=2 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adjzac,"
                           "round(sum(case when row_num<=2 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when row_num<=2 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adjzaz,"
                           "round(sum(case when row_num<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when row_num<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adjzba,"
                           "round(sum(case when row_num<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when row_num<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adjzbb,"
                           "round(sum(case when row_num<=2 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when row_num<=2 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adjzbc,"
                           "round(sum(case when row_num<=2 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when row_num<=2 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adjzbz,"
                           "round(sum(case when row_num<=2 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when row_num<=2 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adjzza,"
                           "round(sum(case when row_num<=2 and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when row_num<=2 and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adjzzb,"
                           "round(sum(case when row_num<=2 and pay_result =1 then amt else 0 end)/sum(case when row_num<=2 and pay_result =1 then count_num else 0 end), 2) as t01adjzzc,"
                           "round(sum(case when row_num<=2 then amt else 0 end)/sum(case when row_num<=2 then count_num else 0 end), 2) as t01adjzzz,"
                           "round(sum(case when row_num<=3 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when row_num<=3 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adkzaa,"
                           "round(sum(case when row_num<=3 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when row_num<=3 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adkzab,"
                           "round(sum(case when row_num<=3 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when row_num<=3 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adkzac,"
                           "round(sum(case when row_num<=3 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when row_num<=3 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adkzaz,"
                           "round(sum(case when row_num<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when row_num<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adkzba,"
                           "round(sum(case when row_num<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when row_num<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adkzbb,"
                           "round(sum(case when row_num<=3 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when row_num<=3 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adkzbc,"
                           "round(sum(case when row_num<=3 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when row_num<=3 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adkzbz,"
                           "round(sum(case when row_num<=3 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when row_num<=3 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adkzza,"
                           "round(sum(case when row_num<=3 and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when row_num<=3 and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adkzzb,"
                           "round(sum(case when row_num<=3 and pay_result =1 then amt else 0 end)/sum(case when row_num<=3 and pay_result =1 then count_num else 0 end), 2) as t01adkzzc,"
                           "round(sum(case when row_num<=3 then amt else 0 end)/sum(case when row_num<=3 then count_num else 0 end), 2) as t01adkzzz,"
                           "round(sum(case when row_num<=4 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when row_num<=4 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adlzaa,"
                           "round(sum(case when row_num<=4 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when row_num<=4 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adlzab,"
                           "round(sum(case when row_num<=4 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when row_num<=4 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adlzac,"
                           "round(sum(case when row_num<=4 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when row_num<=4 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adlzaz,"
                           "round(sum(case when row_num<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when row_num<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adlzba,"
                           "round(sum(case when row_num<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when row_num<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adlzbb,"
                           "round(sum(case when row_num<=4 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when row_num<=4 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adlzbc,"
                           "round(sum(case when row_num<=4 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when row_num<=4 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adlzbz,"
                           "round(sum(case when row_num<=4 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when row_num<=4 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adlzza,"
                           "round(sum(case when row_num<=4 and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when row_num<=4 and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adlzzb,"
                           "round(sum(case when row_num<=4 and pay_result =1 then amt else 0 end)/sum(case when row_num<=4 and pay_result =1 then count_num else 0 end), 2) as t01adlzzc,"
                           "round(sum(case when row_num<=4 then amt else 0 end)/sum(case when row_num<=4 then count_num else 0 end), 2) as t01adlzzz,"
                           "round(sum(case when goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzzaa,"
                           "round(sum(case when goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adzzab,"
                           "round(sum(case when goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adzzac,"
                           "round(sum(case when goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adzzaz,"
                           "round(sum(case when goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzzba,"
                           "round(sum(case when goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adzzbb,"
                           "round(sum(case when goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adzzbc,"
                           "round(sum(case when goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adzzbz,"
                           "round(sum(case when pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzzza,"
                           "round(sum(case when pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adzzzb,"
                           "round(sum(case when pay_result =1 then amt else 0 end)/sum(case when pay_result =1 then count_num else 0 end), 2) as t01adzzzc,"
                           "round(sum(amt)/sum(count_num), 2) as t01adzzzz,"
                           "round(sum(case when day_open<=1 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=1 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzaaa,"
                           "round(sum(case when day_open<=1 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_open<=1 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adzaab,"
                           "round(sum(case when day_open<=1 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when day_open<=1 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adzaac,"
                           "round(sum(case when day_open<=1 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when day_open<=1 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adzaaz,"
                           "round(sum(case when day_open<=1 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=1 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzaba,"
                           "round(sum(case when day_open<=1 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_open<=1 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adzabb,"
                           "round(sum(case when day_open<=1 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when day_open<=1 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adzabc,"
                           "round(sum(case when day_open<=1 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when day_open<=1 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adzabz,"
                           "round(sum(case when day_open<=1 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=1 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzaza,"
                           "round(sum(case when day_open<=1 and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_open<=1 and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adzazb,"
                           "round(sum(case when day_open<=1 and pay_result =1 then amt else 0 end)/sum(case when day_open<=1 and pay_result =1 then count_num else 0 end), 2) as t01adzazc,"
                           "round(sum(case when day_open<=1 then amt else 0 end)/sum(case when day_open<=1 then count_num else 0 end), 2) as t01adzazz,"
                           "round(sum(case when day_open<=2 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=2 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzbaa,"
                           "round(sum(case when day_open<=2 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_open<=2 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adzbab,"
                           "round(sum(case when day_open<=2 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when day_open<=2 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adzbac,"
                           "round(sum(case when day_open<=2 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when day_open<=2 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adzbaz,"
                           "round(sum(case when day_open<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzbba,"
                           "round(sum(case when day_open<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_open<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adzbbb,"
                           "round(sum(case when day_open<=2 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when day_open<=2 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adzbbc,"
                           "round(sum(case when day_open<=2 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when day_open<=2 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adzbbz,"
                           "round(sum(case when day_open<=2 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=2 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzbza,"
                           "round(sum(case when day_open<=2 and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_open<=2 and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adzbzb,"
                           "round(sum(case when day_open<=2 and pay_result =1 then amt else 0 end)/sum(case when day_open<=2 and pay_result =1 then count_num else 0 end), 2) as t01adzbzc,"
                           "round(sum(case when day_open<=2 then amt else 0 end)/sum(case when day_open<=2 then count_num else 0 end), 2) as t01adzbzz,"
                           "round(sum(case when day_open<=3 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=3 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzcaa,"
                           "round(sum(case when day_open<=3 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_open<=3 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adzcab,"
                           "round(sum(case when day_open<=3 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when day_open<=3 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adzcac,"
                           "round(sum(case when day_open<=3 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when day_open<=3 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adzcaz,"
                           "round(sum(case when day_open<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzcba,"
                           "round(sum(case when day_open<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_open<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adzcbb,"
                           "round(sum(case when day_open<=3 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when day_open<=3 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adzcbc,"
                           "round(sum(case when day_open<=3 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when day_open<=3 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adzcbz,"
                           "round(sum(case when day_open<=3 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=3 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzcza,"
                           "round(sum(case when day_open<=3 and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_open<=3 and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adzczb,"
                           "round(sum(case when day_open<=3 and pay_result =1 then amt else 0 end)/sum(case when day_open<=3 and pay_result =1 then count_num else 0 end), 2) as t01adzczc,"
                           "round(sum(case when day_open<=3 then amt else 0 end)/sum(case when day_open<=3 then count_num else 0 end), 2) as t01adzczz,"
                           "round(sum(case when day_open<=4 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=4 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzdaa,"
                           "round(sum(case when day_open<=4 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_open<=4 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adzdab,"
                           "round(sum(case when day_open<=4 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when day_open<=4 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adzdac,"
                           "round(sum(case when day_open<=4 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when day_open<=4 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adzdaz,"
                           "round(sum(case when day_open<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzdba,"
                           "round(sum(case when day_open<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_open<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adzdbb,"
                           "round(sum(case when day_open<=4 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when day_open<=4 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adzdbc,"
                           "round(sum(case when day_open<=4 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when day_open<=4 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adzdbz,"
                           "round(sum(case when day_open<=4 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=4 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzdza,"
                           "round(sum(case when day_open<=4 and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_open<=4 and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adzdzb,"
                           "round(sum(case when day_open<=4 and pay_result =1 then amt else 0 end)/sum(case when day_open<=4 and pay_result =1 then count_num else 0 end), 2) as t01adzdzc,"
                           "round(sum(case when day_open<=4 then amt else 0 end)/sum(case when day_open<=4 then count_num else 0 end), 2) as t01adzdzz,"
                           "round(sum(case when day_open<=5 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=5 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzeaa,"
                           "round(sum(case when day_open<=5 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_open<=5 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adzeab,"
                           "round(sum(case when day_open<=5 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when day_open<=5 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adzeac,"
                           "round(sum(case when day_open<=5 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when day_open<=5 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adzeaz,"
                           "round(sum(case when day_open<=5 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=5 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzeba,"
                           "round(sum(case when day_open<=5 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_open<=5 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adzebb,"
                           "round(sum(case when day_open<=5 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when day_open<=5 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adzebc,"
                           "round(sum(case when day_open<=5 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when day_open<=5 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adzebz,"
                           "round(sum(case when day_open<=5 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=5 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzeza,"
                           "round(sum(case when day_open<=5 and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_open<=5 and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adzezb,"
                           "round(sum(case when day_open<=5 and pay_result =1 then amt else 0 end)/sum(case when day_open<=5 and pay_result =1 then count_num else 0 end), 2) as t01adzezc,"
                           "round(sum(case when day_open<=5 then amt else 0 end)/sum(case when day_open<=5 then count_num else 0 end), 2) as t01adzezz,"
                           "round(sum(case when day_open<=6 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=6 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzfaa,"
                           "round(sum(case when day_open<=6 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_open<=6 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adzfab,"
                           "round(sum(case when day_open<=6 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when day_open<=6 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adzfac,"
                           "round(sum(case when day_open<=6 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when day_open<=6 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adzfaz,"
                           "round(sum(case when day_open<=6 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=6 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzfba,"
                           "round(sum(case when day_open<=6 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_open<=6 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adzfbb,"
                           "round(sum(case when day_open<=6 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when day_open<=6 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adzfbc,"
                           "round(sum(case when day_open<=6 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when day_open<=6 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adzfbz,"
                           "round(sum(case when day_open<=6 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=6 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzfza,"
                           "round(sum(case when day_open<=6 and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_open<=6 and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adzfzb,"
                           "round(sum(case when day_open<=6 and pay_result =1 then amt else 0 end)/sum(case when day_open<=6 and pay_result =1 then count_num else 0 end), 2) as t01adzfzc,"
                           "round(sum(case when day_open<=6 then amt else 0 end)/sum(case when day_open<=6 then count_num else 0 end), 2) as t01adzfzz,"
                           "round(sum(case when day_open<=7 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=7 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzgaa,"
                           "round(sum(case when day_open<=7 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_open<=7 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adzgab,"
                           "round(sum(case when day_open<=7 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when day_open<=7 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adzgac,"
                           "round(sum(case when day_open<=7 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when day_open<=7 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adzgaz,"
                           "round(sum(case when day_open<=7 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=7 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzgba,"
                           "round(sum(case when day_open<=7 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_open<=7 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adzgbb,"
                           "round(sum(case when day_open<=7 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when day_open<=7 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adzgbc,"
                           "round(sum(case when day_open<=7 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when day_open<=7 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adzgbz,"
                           "round(sum(case when day_open<=7 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=7 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzgza,"
                           "round(sum(case when day_open<=7 and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_open<=7 and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adzgzb,"
                           "round(sum(case when day_open<=7 and pay_result =1 then amt else 0 end)/sum(case when day_open<=7 and pay_result =1 then count_num else 0 end), 2) as t01adzgzc,"
                           "round(sum(case when day_open<=7 then amt else 0 end)/sum(case when day_open<=7 then count_num else 0 end), 2) as t01adzgzz,"
                           "round(sum(case when day_open<=8 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=8 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzhaa,"
                           "round(sum(case when day_open<=8 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_open<=8 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adzhab,"
                           "round(sum(case when day_open<=8 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when day_open<=8 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adzhac,"
                           "round(sum(case when day_open<=8 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when day_open<=8 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adzhaz,"
                           "round(sum(case when day_open<=8 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=8 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzhba,"
                           "round(sum(case when day_open<=8 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_open<=8 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adzhbb,"
                           "round(sum(case when day_open<=8 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when day_open<=8 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adzhbc,"
                           "round(sum(case when day_open<=8 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when day_open<=8 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adzhbz,"
                           "round(sum(case when day_open<=8 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=8 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzhza,"
                           "round(sum(case when day_open<=8 and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_open<=8 and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adzhzb,"
                           "round(sum(case when day_open<=8 and pay_result =1 then amt else 0 end)/sum(case when day_open<=8 and pay_result =1 then count_num else 0 end), 2) as t01adzhzc,"
                           "round(sum(case when day_open<=8 then amt else 0 end)/sum(case when day_open<=8 then count_num else 0 end), 2) as t01adzhzz "
                           "from personal_cfsl_loan_deduct_seq_avg_mid yy group by yy.idcard,yy.recall_date")

keySeconds = avgsqlDf.rdd.map(lambda row: dropFrame(row))
keySeconds.repartition(100).saveAsTextFile(output_feature_path_pre + output_path + '/' + key_cal)

sc.stop()

print key_cal + "_sql_daily" + " success " + str(time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()))  +  "*"*90
