#!/usr/bin/python
# encoding:utf-8

# @author:xilin.zheng

# @file:mid.py.py

# @time:2018/11/16 下午4:45
from config import output_sample_data_path_pre,output_feature_path_pre,dropFrame
from pyspark import SparkContext
from pyspark.sql import HiveContext
import sys
import re
import time

reload(sys)
sys.setdefaultencoding('utf-8')

key_cal = 'max'
print key_cal + "_sql_daily" + " run " + str(time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()))  +  "*"*90



sc = SparkContext(appName= key_cal + "_sql_daily")
hsqlContext = HiveContext(sc)

input_path = sys.argv[1]
output_path =  input_path.replace('.csv', '').replace('/*', '')

match_sample_data_path = output_sample_data_path_pre + output_path 


matchRDDS = sc.textFile(match_sample_data_path)

matchRDD = matchRDDS.map(lambda x: x.split(',')).map(lambda row: (
    row[0], row[1], row[2], row[3], row[4], row[5], row[6], row[7], row[8], row[9], row[10], row[11], row[12]))
midDf = hsqlContext.createDataFrame(matchRDD,
                                    ['id_pay', 'idcard', 'no_card', 'no_mec', 'mec_type', 'repay_tm', 'pay_result',
                                     'amt', 'flag_error', 'month', 'day', 'amt_s', 'recall_date'])

hsqlContext.registerDataFrameAsTable(midDf, "personal_cfsl_loan_deduct_seq")

midsqlDf = hsqlContext.sql("select aa.idcard,"
                           "aa.recall_date,"
                           "mec_type as goods_if_subbizcatname,"
                           "case when flag_error = 1 then 1 when flag_error > 1 then 2 else 3 end as req_if_trademsg,"
                           "pay_result as pay_result,"
                           "amt as amt,"
                           "datediff(aa.recall_date, first_value(repay_tm) over(partition by no_mec,aa.idcard,aa.recall_date order by repay_tm)) as day_open,"
                           "datediff(aa.recall_date, repay_tm) as day_pay,"
                           "row_number() over (partition by aa.idcard,aa.recall_date order by repay_tm desc ) as row_num "
                           "from personal_cfsl_loan_deduct_seq aa ")

hsqlContext.registerDataFrameAsTable(midsqlDf, "personal_cfsl_loan_deduct_seq_mid")

maxMidDf = hsqlContext.sql("select idcard,"
                           "recall_date,"
                           "goods_if_subbizcatname,"
                           "req_if_trademsg,"
                           "pay_result,"
                           "case when day_open <= 1 then 1 when day_open <= 7 then 2 when day_open <= 14 then 3 when day_open <= 21 then 4 when day_open <= 30 then 5 when day_open <= 90 then 6 when day_open <= 180 then 7 when day_open <= 360 then 8 else 9 end as day_open,"
                           "case when day_pay <= 1 then 1 when day_pay <= 7 then 2 when day_pay <= 14 then 3 when day_pay <= 21 then 4 when day_pay <= 30 then 5 when day_pay <= 90 then 6 when day_pay <= 180 then 7 when day_pay <= 360 then 8 else 9 end as day_pay,"
                           "case when row_num <= 5 then 1 when row_num <= 20 then 2 when row_num <= 50 then 3 when row_num <= 100 then 4 else 5 end as row_num,"
                           "max(amt) as amt,"
                           "max(day_pay) as max_day_pay "
                           "from personal_cfsl_loan_deduct_seq_mid yy "
                           "group by idcard,"
                           "recall_date,"
                           "goods_if_subbizcatname,"
                           "req_if_trademsg,"
                           "pay_result,"
                           "case when day_open <= 1 then 1 when day_open <= 7 then 2 when day_open <= 14 then 3 when day_open <= 21 then 4 when day_open <= 30 then 5 when day_open <= 90 then 6 when day_open <= 180 then 7 when day_open <= 360 then 8 else 9 end,"
                           "case when day_pay <= 1 then 1 when day_pay <= 7 then 2 when day_pay <= 14 then 3 when day_pay <= 21 then 4 when day_pay <= 30 then 5 when day_pay <= 90 then 6 when day_pay <= 180 then 7 when day_pay <= 360 then 8 else 9 end,"
                           "case when row_num <= 5 then 1 when row_num <= 20 then 2 when row_num <= 50 then 3 when row_num <= 100 then 4 else 5 end")

hsqlContext.registerDataFrameAsTable(maxMidDf, "personal_cfsl_loan_deduct_seq_max_mid")

maxsqlDf = hsqlContext.sql("select idcard,recall_date,"
                           "round(max(case when day_pay<=1 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aaazaa,"
                           "round(max(case when day_pay<=1 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aaazab,"
                           "round(max(case when day_pay<=1 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aaazac,"
                           "round(max(case when day_pay<=1 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aaazaz,"
                           "round(max(case when day_pay<=1 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aaazba,"
                           "round(max(case when day_pay<=1 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aaazbb,"
                           "round(max(case when day_pay<=1 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aaazbc,"
                           "round(max(case when day_pay<=1 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aaazbz,"
                           "round(max(case when day_pay<=1 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aaazza,"
                           "round(max(case when day_pay<=1 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aaazzb,"
                           "round(max(case when day_pay<=1 and pay_result =1 then amt else null end), 2) as t01aaazzc,"
                           "round(max(case when day_pay<=1 then amt else null end), 2) as t01aaazzz,"
                           "round(max(case when day_pay<=2 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aabzaa,"
                           "round(max(case when day_pay<=2 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aabzab,"
                           "round(max(case when day_pay<=2 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aabzac,"
                           "round(max(case when day_pay<=2 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aabzaz,"
                           "round(max(case when day_pay<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aabzba,"
                           "round(max(case when day_pay<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aabzbb,"
                           "round(max(case when day_pay<=2 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aabzbc,"
                           "round(max(case when day_pay<=2 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aabzbz,"
                           "round(max(case when day_pay<=2 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aabzza,"
                           "round(max(case when day_pay<=2 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aabzzb,"
                           "round(max(case when day_pay<=2 and pay_result =1 then amt else null end), 2) as t01aabzzc,"
                           "round(max(case when day_pay<=2 then amt else null end), 2) as t01aabzzz,"
                           "round(max(case when day_pay<=3 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aaczaa,"
                           "round(max(case when day_pay<=3 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aaczab,"
                           "round(max(case when day_pay<=3 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aaczac,"
                           "round(max(case when day_pay<=3 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aaczaz,"
                           "round(max(case when day_pay<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aaczba,"
                           "round(max(case when day_pay<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aaczbb,"
                           "round(max(case when day_pay<=3 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aaczbc,"
                           "round(max(case when day_pay<=3 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aaczbz,"
                           "round(max(case when day_pay<=3 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aaczza,"
                           "round(max(case when day_pay<=3 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aaczzb,"
                           "round(max(case when day_pay<=3 and pay_result =1 then amt else null end), 2) as t01aaczzc,"
                           "round(max(case when day_pay<=3 then amt else null end), 2) as t01aaczzz,"
                           "round(max(case when day_pay<=4 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aadzaa,"
                           "round(max(case when day_pay<=4 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aadzab,"
                           "round(max(case when day_pay<=4 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aadzac,"
                           "round(max(case when day_pay<=4 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aadzaz,"
                           "round(max(case when day_pay<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aadzba,"
                           "round(max(case when day_pay<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aadzbb,"
                           "round(max(case when day_pay<=4 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aadzbc,"
                           "round(max(case when day_pay<=4 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aadzbz,"
                           "round(max(case when day_pay<=4 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aadzza,"
                           "round(max(case when day_pay<=4 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aadzzb,"
                           "round(max(case when day_pay<=4 and pay_result =1 then amt else null end), 2) as t01aadzzc,"
                           "round(max(case when day_pay<=4 then amt else null end), 2) as t01aadzzz,"
                           "round(max(case when day_pay<=5 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aaezaa,"
                           "round(max(case when day_pay<=5 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aaezab,"
                           "round(max(case when day_pay<=5 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aaezac,"
                           "round(max(case when day_pay<=5 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aaezaz,"
                           "round(max(case when day_pay<=5 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aaezba,"
                           "round(max(case when day_pay<=5 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aaezbb,"
                           "round(max(case when day_pay<=5 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aaezbc,"
                           "round(max(case when day_pay<=5 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aaezbz,"
                           "round(max(case when day_pay<=5 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aaezza,"
                           "round(max(case when day_pay<=5 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aaezzb,"
                           "round(max(case when day_pay<=5 and pay_result =1 then amt else null end), 2) as t01aaezzc,"
                           "round(max(case when day_pay<=5 then amt else null end), 2) as t01aaezzz,"
                           "round(max(case when day_pay<=6 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aafzaa,"
                           "round(max(case when day_pay<=6 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aafzab,"
                           "round(max(case when day_pay<=6 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aafzac,"
                           "round(max(case when day_pay<=6 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aafzaz,"
                           "round(max(case when day_pay<=6 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aafzba,"
                           "round(max(case when day_pay<=6 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aafzbb,"
                           "round(max(case when day_pay<=6 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aafzbc,"
                           "round(max(case when day_pay<=6 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aafzbz,"
                           "round(max(case when day_pay<=6 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aafzza,"
                           "round(max(case when day_pay<=6 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aafzzb,"
                           "round(max(case when day_pay<=6 and pay_result =1 then amt else null end), 2) as t01aafzzc,"
                           "round(max(case when day_pay<=6 then amt else null end), 2) as t01aafzzz,"
                           "round(max(case when day_pay<=7 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aagzaa,"
                           "round(max(case when day_pay<=7 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aagzab,"
                           "round(max(case when day_pay<=7 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aagzac,"
                           "round(max(case when day_pay<=7 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aagzaz,"
                           "round(max(case when day_pay<=7 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aagzba,"
                           "round(max(case when day_pay<=7 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aagzbb,"
                           "round(max(case when day_pay<=7 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aagzbc,"
                           "round(max(case when day_pay<=7 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aagzbz,"
                           "round(max(case when day_pay<=7 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aagzza,"
                           "round(max(case when day_pay<=7 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aagzzb,"
                           "round(max(case when day_pay<=7 and pay_result =1 then amt else null end), 2) as t01aagzzc,"
                           "round(max(case when day_pay<=7 then amt else null end), 2) as t01aagzzz,"
                           "round(max(case when day_pay<=8 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aahzaa,"
                           "round(max(case when day_pay<=8 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aahzab,"
                           "round(max(case when day_pay<=8 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aahzac,"
                           "round(max(case when day_pay<=8 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aahzaz,"
                           "round(max(case when day_pay<=8 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aahzba,"
                           "round(max(case when day_pay<=8 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aahzbb,"
                           "round(max(case when day_pay<=8 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aahzbc,"
                           "round(max(case when day_pay<=8 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aahzbz,"
                           "round(max(case when day_pay<=8 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aahzza,"
                           "round(max(case when day_pay<=8 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aahzzb,"
                           "round(max(case when day_pay<=8 and pay_result =1 then amt else null end), 2) as t01aahzzc,"
                           "round(max(case when day_pay<=8 then amt else null end), 2) as t01aahzzz,"
                           "round(max(case when row_num<=1 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aaizaa,"
                           "round(max(case when row_num<=1 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aaizab,"
                           "round(max(case when row_num<=1 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aaizac,"
                           "round(max(case when row_num<=1 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aaizaz,"
                           "round(max(case when row_num<=1 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aaizba,"
                           "round(max(case when row_num<=1 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aaizbb,"
                           "round(max(case when row_num<=1 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aaizbc,"
                           "round(max(case when row_num<=1 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aaizbz,"
                           "round(max(case when row_num<=1 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aaizza,"
                           "round(max(case when row_num<=1 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aaizzb,"
                           "round(max(case when row_num<=1 and pay_result =1 then amt else null end), 2) as t01aaizzc,"
                           "round(max(case when row_num<=1 then amt else null end), 2) as t01aaizzz,"
                           "round(max(case when row_num<=2 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aajzaa,"
                           "round(max(case when row_num<=2 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aajzab,"
                           "round(max(case when row_num<=2 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aajzac,"
                           "round(max(case when row_num<=2 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aajzaz,"
                           "round(max(case when row_num<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aajzba,"
                           "round(max(case when row_num<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aajzbb,"
                           "round(max(case when row_num<=2 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aajzbc,"
                           "round(max(case when row_num<=2 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aajzbz,"
                           "round(max(case when row_num<=2 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aajzza,"
                           "round(max(case when row_num<=2 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aajzzb,"
                           "round(max(case when row_num<=2 and pay_result =1 then amt else null end), 2) as t01aajzzc,"
                           "round(max(case when row_num<=2 then amt else null end), 2) as t01aajzzz,"
                           "round(max(case when row_num<=3 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aakzaa,"
                           "round(max(case when row_num<=3 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aakzab,"
                           "round(max(case when row_num<=3 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aakzac,"
                           "round(max(case when row_num<=3 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aakzaz,"
                           "round(max(case when row_num<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aakzba,"
                           "round(max(case when row_num<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aakzbb,"
                           "round(max(case when row_num<=3 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aakzbc,"
                           "round(max(case when row_num<=3 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aakzbz,"
                           "round(max(case when row_num<=3 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aakzza,"
                           "round(max(case when row_num<=3 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aakzzb,"
                           "round(max(case when row_num<=3 and pay_result =1 then amt else null end), 2) as t01aakzzc,"
                           "round(max(case when row_num<=3 then amt else null end), 2) as t01aakzzz,"
                           "round(max(case when row_num<=4 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aalzaa,"
                           "round(max(case when row_num<=4 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aalzab,"
                           "round(max(case when row_num<=4 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aalzac,"
                           "round(max(case when row_num<=4 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aalzaz,"
                           "round(max(case when row_num<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aalzba,"
                           "round(max(case when row_num<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aalzbb,"
                           "round(max(case when row_num<=4 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aalzbc,"
                           "round(max(case when row_num<=4 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aalzbz,"
                           "round(max(case when row_num<=4 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aalzza,"
                           "round(max(case when row_num<=4 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aalzzb,"
                           "round(max(case when row_num<=4 and pay_result =1 then amt else null end), 2) as t01aalzzc,"
                           "round(max(case when row_num<=4 then amt else null end), 2) as t01aalzzz,"
                           "round(max(case when goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazzaa,"
                           "round(max(case when goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aazzab,"
                           "round(max(case when goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aazzac,"
                           "round(max(case when goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aazzaz,"
                           "round(max(case when goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazzba,"
                           "round(max(case when goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aazzbb,"
                           "round(max(case when goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aazzbc,"
                           "round(max(case when goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aazzbz,"
                           "round(max(case when pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazzza,"
                           "round(max(case when pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aazzzb,"
                           "round(max(case when pay_result =1 then amt else null end), 2) as t01aazzzc,"
                           "round(max(amt), 2) as t01aazzzz,"
                           "round(max(case when goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then max_day_pay else null end)) as t01bazzaa,"
                           "round(max(case when goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then max_day_pay else null end)) as t01bazzab,"
                           "round(max(case when goods_if_subbizcatname = 'cf' and pay_result =1 then max_day_pay else null end)) as t01bazzac,"
                           "round(max(case when goods_if_subbizcatname = 'cf' then max_day_pay else null end)) as t01bazzaz,"
                           "round(max(case when goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then max_day_pay else null end)) as t01bazzba,"
                           "round(max(case when goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then max_day_pay else null end)) as t01bazzbb,"
                           "round(max(case when goods_if_subbizcatname ='sl' and pay_result =1 then max_day_pay else null end)) as t01bazzbc,"
                           "round(max(case when goods_if_subbizcatname ='sl' then max_day_pay else null end)) as t01bazzbz,"
                           "round(max(case when pay_result =0 and req_if_trademsg = 1 then max_day_pay else null end)) as t01bazzza,"
                           "round(max(case when pay_result =0 and req_if_trademsg = 2 then max_day_pay else null end)) as t01bazzzb,"
                           "round(max(case when pay_result =1 then max_day_pay else null end)) as t01bazzzc,"
                           "round(max(max_day_pay)) as t01bazzzz,"
                           "round(max(case when day_open<=1 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazaaa,"
                           "round(max(case when day_open<=1 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aazaab,"
                           "round(max(case when day_open<=1 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aazaac,"
                           "round(max(case when day_open<=1 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aazaaz,"
                           "round(max(case when day_open<=1 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazaba,"
                           "round(max(case when day_open<=1 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aazabb,"
                           "round(max(case when day_open<=1 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aazabc,"
                           "round(max(case when day_open<=1 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aazabz,"
                           "round(max(case when day_open<=1 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazaza,"
                           "round(max(case when day_open<=1 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aazazb,"
                           "round(max(case when day_open<=1 and pay_result =1 then amt else null end), 2) as t01aazazc,"
                           "round(max(case when day_open<=1 then amt else null end), 2) as t01aazazz,"
                           "round(max(case when day_open<=2 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazbaa,"
                           "round(max(case when day_open<=2 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aazbab,"
                           "round(max(case when day_open<=2 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aazbac,"
                           "round(max(case when day_open<=2 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aazbaz,"
                           "round(max(case when day_open<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazbba,"
                           "round(max(case when day_open<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aazbbb,"
                           "round(max(case when day_open<=2 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aazbbc,"
                           "round(max(case when day_open<=2 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aazbbz,"
                           "round(max(case when day_open<=2 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazbza,"
                           "round(max(case when day_open<=2 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aazbzb,"
                           "round(max(case when day_open<=2 and pay_result =1 then amt else null end), 2) as t01aazbzc,"
                           "round(max(case when day_open<=2 then amt else null end), 2) as t01aazbzz,"
                           "round(max(case when day_open<=3 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazcaa,"
                           "round(max(case when day_open<=3 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aazcab,"
                           "round(max(case when day_open<=3 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aazcac,"
                           "round(max(case when day_open<=3 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aazcaz,"
                           "round(max(case when day_open<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazcba,"
                           "round(max(case when day_open<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aazcbb,"
                           "round(max(case when day_open<=3 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aazcbc,"
                           "round(max(case when day_open<=3 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aazcbz,"
                           "round(max(case when day_open<=3 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazcza,"
                           "round(max(case when day_open<=3 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aazczb,"
                           "round(max(case when day_open<=3 and pay_result =1 then amt else null end), 2) as t01aazczc,"
                           "round(max(case when day_open<=3 then amt else null end), 2) as t01aazczz,"
                           "round(max(case when day_open<=4 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazdaa,"
                           "round(max(case when day_open<=4 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aazdab,"
                           "round(max(case when day_open<=4 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aazdac,"
                           "round(max(case when day_open<=4 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aazdaz,"
                           "round(max(case when day_open<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazdba,"
                           "round(max(case when day_open<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aazdbb,"
                           "round(max(case when day_open<=4 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aazdbc,"
                           "round(max(case when day_open<=4 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aazdbz,"
                           "round(max(case when day_open<=4 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazdza,"
                           "round(max(case when day_open<=4 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aazdzb,"
                           "round(max(case when day_open<=4 and pay_result =1 then amt else null end), 2) as t01aazdzc,"
                           "round(max(case when day_open<=4 then amt else null end), 2) as t01aazdzz,"
                           "round(max(case when day_open<=5 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazeaa,"
                           "round(max(case when day_open<=5 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aazeab,"
                           "round(max(case when day_open<=5 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aazeac,"
                           "round(max(case when day_open<=5 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aazeaz,"
                           "round(max(case when day_open<=5 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazeba,"
                           "round(max(case when day_open<=5 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aazebb,"
                           "round(max(case when day_open<=5 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aazebc,"
                           "round(max(case when day_open<=5 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aazebz,"
                           "round(max(case when day_open<=5 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazeza,"
                           "round(max(case when day_open<=5 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aazezb,"
                           "round(max(case when day_open<=5 and pay_result =1 then amt else null end), 2) as t01aazezc,"
                           "round(max(case when day_open<=5 then amt else null end), 2) as t01aazezz,"
                           "round(max(case when day_open<=6 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazfaa,"
                           "round(max(case when day_open<=6 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aazfab,"
                           "round(max(case when day_open<=6 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aazfac,"
                           "round(max(case when day_open<=6 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aazfaz,"
                           "round(max(case when day_open<=6 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazfba,"
                           "round(max(case when day_open<=6 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aazfbb,"
                           "round(max(case when day_open<=6 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aazfbc,"
                           "round(max(case when day_open<=6 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aazfbz,"
                           "round(max(case when day_open<=6 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazfza,"
                           "round(max(case when day_open<=6 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aazfzb,"
                           "round(max(case when day_open<=6 and pay_result =1 then amt else null end), 2) as t01aazfzc,"
                           "round(max(case when day_open<=6 then amt else null end), 2) as t01aazfzz,"
                           "round(max(case when day_open<=7 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazgaa,"
                           "round(max(case when day_open<=7 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aazgab,"
                           "round(max(case when day_open<=7 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aazgac,"
                           "round(max(case when day_open<=7 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aazgaz,"
                           "round(max(case when day_open<=7 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazgba,"
                           "round(max(case when day_open<=7 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aazgbb,"
                           "round(max(case when day_open<=7 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aazgbc,"
                           "round(max(case when day_open<=7 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aazgbz,"
                           "round(max(case when day_open<=7 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazgza,"
                           "round(max(case when day_open<=7 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aazgzb,"
                           "round(max(case when day_open<=7 and pay_result =1 then amt else null end), 2) as t01aazgzc,"
                           "round(max(case when day_open<=7 then amt else null end), 2) as t01aazgzz,"
                           "round(max(case when day_open<=8 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazhaa,"
                           "round(max(case when day_open<=8 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aazhab,"
                           "round(max(case when day_open<=8 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aazhac,"
                           "round(max(case when day_open<=8 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aazhaz,"
                           "round(max(case when day_open<=8 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazhba,"
                           "round(max(case when day_open<=8 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aazhbb,"
                           "round(max(case when day_open<=8 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aazhbc,"
                           "round(max(case when day_open<=8 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aazhbz,"
                           "round(max(case when day_open<=8 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazhza,"
                           "round(max(case when day_open<=8 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aazhzb,"
                           "round(max(case when day_open<=8 and pay_result =1 then amt else null end), 2) as t01aazhzc,"
                           "round(max(case when day_open<=8 then amt else null end), 2) as t01aazhzz "
                           "from personal_cfsl_loan_deduct_seq_max_mid yy group by yy.idcard,yy.recall_date")

keySeconds = maxsqlDf.rdd.map(lambda row: dropFrame(row))
keySeconds.repartition(100).saveAsTextFile(output_feature_path_pre + output_path + '/' + key_cal)
sc.stop()

print key_cal + "_sql_daily" + " success " + str(time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()))  +  "*"*90

