#!/usr/bin/python
# encoding:utf-8

# @author:xilin.zheng

# @file:mid.py.py

# @time:2018/11/16 下午4:45
from config import output_sample_data_path_pre,output_feature_path_pre,dropFrame
from pyspark import SparkContext
from pyspark.sql import HiveContext
import sys
import re
import time

reload(sys)
sys.setdefaultencoding('utf-8')

key_cal = 'min'
print key_cal + "_sql_daily" + " run " + str(time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()))  +  "*"*90



sc = SparkContext(appName= key_cal + "_sql_daily")
hsqlContext = HiveContext(sc)

input_path = sys.argv[1]
output_path =  input_path.replace('.csv', '').replace('/*', '')

match_sample_data_path = output_sample_data_path_pre + output_path 


matchRDDS = sc.textFile(match_sample_data_path)

matchRDD = matchRDDS.map(lambda x: x.split(',')).map(lambda row: (
    row[0], row[1], row[2], row[3], row[4], row[5], row[6], row[7], row[8], row[9], row[10], row[11], row[12]))
midDf = hsqlContext.createDataFrame(matchRDD,
                                    ['id_pay', 'idcard', 'no_card', 'no_mec', 'mec_type', 'repay_tm', 'pay_result',
                                     'amt', 'flag_error', 'month', 'day', 'amt_s', 'recall_date'])

hsqlContext.registerDataFrameAsTable(midDf, "personal_cfsl_loan_deduct_seq")


midsqlDf = hsqlContext.sql("select aa.idcard,"
                           "aa.recall_date,"
                           "mec_type as goods_if_subbizcatname,"
                           "case when flag_error = 1 then 1 when flag_error > 1 then 2 else 3 end as req_if_trademsg,"
                           "pay_result as pay_result,"
                           "amt as amt,"
                           "datediff(aa.recall_date, first_value(repay_tm) over(partition by no_mec,aa.idcard,aa.recall_date order by repay_tm)) as day_open,"
                           "datediff(aa.recall_date, repay_tm) as day_pay,"
                           "row_number() over (partition by aa.idcard,aa.recall_date order by repay_tm desc ) as row_num "
                           "from personal_cfsl_loan_deduct_seq aa ")

hsqlContext.registerDataFrameAsTable(midsqlDf, "personal_cfsl_loan_deduct_seq_mid")

minMidDf = hsqlContext.sql("select idcard,"
                           "recall_date,"
                           "goods_if_subbizcatname,"
                           "req_if_trademsg,"
                           "pay_result,"
                           "case when day_open <= 1 then 1 when day_open <= 7 then 2 when day_open <= 14 then 3 when day_open <= 21 then 4 when day_open <= 30 then 5 when day_open <= 90 then 6 when day_open <= 180 then 7 when day_open <= 360 then 8 else 9 end as day_open,"
                           "case when day_pay <= 1 then 1 when day_pay <= 7 then 2 when day_pay <= 14 then 3 when day_pay <= 21 then 4 when day_pay <= 30 then 5 when day_pay <= 90 then 6 when day_pay <= 180 then 7 when day_pay <= 360 then 8 else 9 end as day_pay,"
                           "case when row_num <= 5 then 1 when row_num <= 20 then 2 when row_num <= 50 then 3 when row_num <= 100 then 4 else 5 end as row_num,"
                           "min(amt) as amt,"
                           "min(day_pay) as min_day_pay "
                           "from personal_cfsl_loan_deduct_seq_mid yy "
                           "group by idcard,"
                           "recall_date,"
                           "goods_if_subbizcatname,"
                           "req_if_trademsg,"
                           "pay_result,"
                           "case when day_open <= 1 then 1 when day_open <= 7 then 2 when day_open <= 14 then 3 when day_open <= 21 then 4 when day_open <= 30 then 5 when day_open <= 90 then 6 when day_open <= 180 then 7 when day_open <= 360 then 8 else 9 end,"
                           "case when day_pay <= 1 then 1 when day_pay <= 7 then 2 when day_pay <= 14 then 3 when day_pay <= 21 then 4 when day_pay <= 30 then 5 when day_pay <= 90 then 6 when day_pay <= 180 then 7 when day_pay <= 360 then 8 else 9 end,"
                           "case when row_num <= 5 then 1 when row_num <= 20 then 2 when row_num <= 50 then 3 when row_num <= 100 then 4 else 5 end")

hsqlContext.registerDataFrameAsTable(minMidDf, "personal_cfsl_loan_deduct_seq_min_mid")

minsqlDf = hsqlContext.sql("select idcard,recall_date,"
                           "round(min(case when day_pay<=1 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abazaa,"
                           "round(min(case when day_pay<=1 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abazab,"
                           "round(min(case when day_pay<=1 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abazac,"
                           "round(min(case when day_pay<=1 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abazaz,"
                           "round(min(case when day_pay<=1 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abazba,"
                           "round(min(case when day_pay<=1 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abazbb,"
                           "round(min(case when day_pay<=1 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abazbc,"
                           "round(min(case when day_pay<=1 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abazbz,"
                           "round(min(case when day_pay<=1 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abazza,"
                           "round(min(case when day_pay<=1 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abazzb,"
                           "round(min(case when day_pay<=1 and pay_result =1 then amt else null end), 2) as t01abazzc,"
                           "round(min(case when day_pay<=1 then amt else null end), 2) as t01abazzz,"
                           "round(min(case when day_pay<=2 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abbzaa,"
                           "round(min(case when day_pay<=2 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abbzab,"
                           "round(min(case when day_pay<=2 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abbzac,"
                           "round(min(case when day_pay<=2 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abbzaz,"
                           "round(min(case when day_pay<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abbzba,"
                           "round(min(case when day_pay<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abbzbb,"
                           "round(min(case when day_pay<=2 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abbzbc,"
                           "round(min(case when day_pay<=2 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abbzbz,"
                           "round(min(case when day_pay<=2 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abbzza,"
                           "round(min(case when day_pay<=2 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abbzzb,"
                           "round(min(case when day_pay<=2 and pay_result =1 then amt else null end), 2) as t01abbzzc,"
                           "round(min(case when day_pay<=2 then amt else null end), 2) as t01abbzzz,"
                           "round(min(case when day_pay<=3 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abczaa,"
                           "round(min(case when day_pay<=3 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abczab,"
                           "round(min(case when day_pay<=3 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abczac,"
                           "round(min(case when day_pay<=3 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abczaz,"
                           "round(min(case when day_pay<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abczba,"
                           "round(min(case when day_pay<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abczbb,"
                           "round(min(case when day_pay<=3 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abczbc,"
                           "round(min(case when day_pay<=3 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abczbz,"
                           "round(min(case when day_pay<=3 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abczza,"
                           "round(min(case when day_pay<=3 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abczzb,"
                           "round(min(case when day_pay<=3 and pay_result =1 then amt else null end), 2) as t01abczzc,"
                           "round(min(case when day_pay<=3 then amt else null end), 2) as t01abczzz,"
                           "round(min(case when day_pay<=4 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abdzaa,"
                           "round(min(case when day_pay<=4 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abdzab,"
                           "round(min(case when day_pay<=4 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abdzac,"
                           "round(min(case when day_pay<=4 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abdzaz,"
                           "round(min(case when day_pay<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abdzba,"
                           "round(min(case when day_pay<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abdzbb,"
                           "round(min(case when day_pay<=4 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abdzbc,"
                           "round(min(case when day_pay<=4 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abdzbz,"
                           "round(min(case when day_pay<=4 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abdzza,"
                           "round(min(case when day_pay<=4 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abdzzb,"
                           "round(min(case when day_pay<=4 and pay_result =1 then amt else null end), 2) as t01abdzzc,"
                           "round(min(case when day_pay<=4 then amt else null end), 2) as t01abdzzz,"
                           "round(min(case when day_pay<=5 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abezaa,"
                           "round(min(case when day_pay<=5 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abezab,"
                           "round(min(case when day_pay<=5 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abezac,"
                           "round(min(case when day_pay<=5 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abezaz,"
                           "round(min(case when day_pay<=5 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abezba,"
                           "round(min(case when day_pay<=5 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abezbb,"
                           "round(min(case when day_pay<=5 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abezbc,"
                           "round(min(case when day_pay<=5 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abezbz,"
                           "round(min(case when day_pay<=5 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abezza,"
                           "round(min(case when day_pay<=5 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abezzb,"
                           "round(min(case when day_pay<=5 and pay_result =1 then amt else null end), 2) as t01abezzc,"
                           "round(min(case when day_pay<=5 then amt else null end), 2) as t01abezzz,"
                           "round(min(case when day_pay<=6 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abfzaa,"
                           "round(min(case when day_pay<=6 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abfzab,"
                           "round(min(case when day_pay<=6 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abfzac,"
                           "round(min(case when day_pay<=6 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abfzaz,"
                           "round(min(case when day_pay<=6 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abfzba,"
                           "round(min(case when day_pay<=6 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abfzbb,"
                           "round(min(case when day_pay<=6 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abfzbc,"
                           "round(min(case when day_pay<=6 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abfzbz,"
                           "round(min(case when day_pay<=6 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abfzza,"
                           "round(min(case when day_pay<=6 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abfzzb,"
                           "round(min(case when day_pay<=6 and pay_result =1 then amt else null end), 2) as t01abfzzc,"
                           "round(min(case when day_pay<=6 then amt else null end), 2) as t01abfzzz,"
                           "round(min(case when day_pay<=7 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abgzaa,"
                           "round(min(case when day_pay<=7 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abgzab,"
                           "round(min(case when day_pay<=7 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abgzac,"
                           "round(min(case when day_pay<=7 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abgzaz,"
                           "round(min(case when day_pay<=7 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abgzba,"
                           "round(min(case when day_pay<=7 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abgzbb,"
                           "round(min(case when day_pay<=7 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abgzbc,"
                           "round(min(case when day_pay<=7 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abgzbz,"
                           "round(min(case when day_pay<=7 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abgzza,"
                           "round(min(case when day_pay<=7 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abgzzb,"
                           "round(min(case when day_pay<=7 and pay_result =1 then amt else null end), 2) as t01abgzzc,"
                           "round(min(case when day_pay<=7 then amt else null end), 2) as t01abgzzz,"
                           "round(min(case when day_pay<=8 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abhzaa,"
                           "round(min(case when day_pay<=8 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abhzab,"
                           "round(min(case when day_pay<=8 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abhzac,"
                           "round(min(case when day_pay<=8 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abhzaz,"
                           "round(min(case when day_pay<=8 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abhzba,"
                           "round(min(case when day_pay<=8 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abhzbb,"
                           "round(min(case when day_pay<=8 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abhzbc,"
                           "round(min(case when day_pay<=8 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abhzbz,"
                           "round(min(case when day_pay<=8 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abhzza,"
                           "round(min(case when day_pay<=8 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abhzzb,"
                           "round(min(case when day_pay<=8 and pay_result =1 then amt else null end), 2) as t01abhzzc,"
                           "round(min(case when day_pay<=8 then amt else null end), 2) as t01abhzzz,"
                           "round(min(case when row_num<=1 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abizaa,"
                           "round(min(case when row_num<=1 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abizab,"
                           "round(min(case when row_num<=1 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abizac,"
                           "round(min(case when row_num<=1 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abizaz,"
                           "round(min(case when row_num<=1 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abizba,"
                           "round(min(case when row_num<=1 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abizbb,"
                           "round(min(case when row_num<=1 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abizbc,"
                           "round(min(case when row_num<=1 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abizbz,"
                           "round(min(case when row_num<=1 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abizza,"
                           "round(min(case when row_num<=1 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abizzb,"
                           "round(min(case when row_num<=1 and pay_result =1 then amt else null end), 2) as t01abizzc,"
                           "round(min(case when row_num<=1 then amt else null end), 2) as t01abizzz,"
                           "round(min(case when row_num<=2 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abjzaa,"
                           "round(min(case when row_num<=2 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abjzab,"
                           "round(min(case when row_num<=2 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abjzac,"
                           "round(min(case when row_num<=2 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abjzaz,"
                           "round(min(case when row_num<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abjzba,"
                           "round(min(case when row_num<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abjzbb,"
                           "round(min(case when row_num<=2 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abjzbc,"
                           "round(min(case when row_num<=2 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abjzbz,"
                           "round(min(case when row_num<=2 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abjzza,"
                           "round(min(case when row_num<=2 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abjzzb,"
                           "round(min(case when row_num<=2 and pay_result =1 then amt else null end), 2) as t01abjzzc,"
                           "round(min(case when row_num<=2 then amt else null end), 2) as t01abjzzz,"
                           "round(min(case when row_num<=3 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abkzaa,"
                           "round(min(case when row_num<=3 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abkzab,"
                           "round(min(case when row_num<=3 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abkzac,"
                           "round(min(case when row_num<=3 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abkzaz,"
                           "round(min(case when row_num<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abkzba,"
                           "round(min(case when row_num<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abkzbb,"
                           "round(min(case when row_num<=3 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abkzbc,"
                           "round(min(case when row_num<=3 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abkzbz,"
                           "round(min(case when row_num<=3 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abkzza,"
                           "round(min(case when row_num<=3 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abkzzb,"
                           "round(min(case when row_num<=3 and pay_result =1 then amt else null end), 2) as t01abkzzc,"
                           "round(min(case when row_num<=3 then amt else null end), 2) as t01abkzzz,"
                           "round(min(case when row_num<=4 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01ablzaa,"
                           "round(min(case when row_num<=4 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01ablzab,"
                           "round(min(case when row_num<=4 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01ablzac,"
                           "round(min(case when row_num<=4 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01ablzaz,"
                           "round(min(case when row_num<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01ablzba,"
                           "round(min(case when row_num<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01ablzbb,"
                           "round(min(case when row_num<=4 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01ablzbc,"
                           "round(min(case when row_num<=4 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01ablzbz,"
                           "round(min(case when row_num<=4 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01ablzza,"
                           "round(min(case when row_num<=4 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01ablzzb,"
                           "round(min(case when row_num<=4 and pay_result =1 then amt else null end), 2) as t01ablzzc,"
                           "round(min(case when row_num<=4 then amt else null end), 2) as t01ablzzz,"
                           "round(min(case when goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzzaa,"
                           "round(min(case when goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abzzab,"
                           "round(min(case when goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abzzac,"
                           "round(min(case when goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abzzaz,"
                           "round(min(case when goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzzba,"
                           "round(min(case when goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abzzbb,"
                           "round(min(case when goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abzzbc,"
                           "round(min(case when goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abzzbz,"
                           "round(min(case when pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzzza,"
                           "round(min(case when pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abzzzb,"
                           "round(min(case when pay_result =1 then amt else null end), 2) as t01abzzzc,"
                           "round(min(amt)) as t01abzzzz,"
                           "round(min(case when goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then min_day_pay else null end)) as t01bbzzaa,"
                           "round(min(case when goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then min_day_pay else null end)) as t01bbzzab,"
                           "round(min(case when goods_if_subbizcatname = 'cf' and pay_result =1 then min_day_pay else null end)) as t01bbzzac,"
                           "round(min(case when goods_if_subbizcatname = 'cf' then min_day_pay else null end)) as t01bbzzaz,"
                           "round(min(case when goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then min_day_pay else null end)) as t01bbzzba,"
                           "round(min(case when goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then min_day_pay else null end)) as t01bbzzbb,"
                           "round(min(case when goods_if_subbizcatname ='sl' and pay_result =1 then min_day_pay else null end)) as t01bbzzbc,"
                           "round(min(case when goods_if_subbizcatname ='sl' then min_day_pay else null end)) as t01bbzzbz,"
                           "round(min(case when pay_result =0 and req_if_trademsg = 1 then min_day_pay else null end)) as t01bbzzza,"
                           "round(min(case when pay_result =0 and req_if_trademsg = 2 then min_day_pay else null end)) as t01bbzzzb,"
                           "round(min(case when pay_result =1 then min_day_pay else null end)) as t01bbzzzc,"
                           "round(min(min_day_pay)) as t01bbzzzz,"
                           "round(min(case when day_open<=1 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzaaa,"
                           "round(min(case when day_open<=1 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abzaab,"
                           "round(min(case when day_open<=1 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abzaac,"
                           "round(min(case when day_open<=1 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abzaaz,"
                           "round(min(case when day_open<=1 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzaba,"
                           "round(min(case when day_open<=1 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abzabb,"
                           "round(min(case when day_open<=1 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abzabc,"
                           "round(min(case when day_open<=1 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abzabz,"
                           "round(min(case when day_open<=1 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzaza,"
                           "round(min(case when day_open<=1 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abzazb,"
                           "round(min(case when day_open<=1 and pay_result =1 then amt else null end), 2) as t01abzazc,"
                           "round(min(case when day_open<=1 then amt else null end), 2) as t01abzazz,"
                           "round(min(case when day_open<=2 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzbaa,"
                           "round(min(case when day_open<=2 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abzbab,"
                           "round(min(case when day_open<=2 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abzbac,"
                           "round(min(case when day_open<=2 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abzbaz,"
                           "round(min(case when day_open<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzbba,"
                           "round(min(case when day_open<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abzbbb,"
                           "round(min(case when day_open<=2 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abzbbc,"
                           "round(min(case when day_open<=2 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abzbbz,"
                           "round(min(case when day_open<=2 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzbza,"
                           "round(min(case when day_open<=2 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abzbzb,"
                           "round(min(case when day_open<=2 and pay_result =1 then amt else null end), 2) as t01abzbzc,"
                           "round(min(case when day_open<=2 then amt else null end), 2) as t01abzbzz,"
                           "round(min(case when day_open<=3 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzcaa,"
                           "round(min(case when day_open<=3 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abzcab,"
                           "round(min(case when day_open<=3 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abzcac,"
                           "round(min(case when day_open<=3 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abzcaz,"
                           "round(min(case when day_open<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzcba,"
                           "round(min(case when day_open<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abzcbb,"
                           "round(min(case when day_open<=3 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abzcbc,"
                           "round(min(case when day_open<=3 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abzcbz,"
                           "round(min(case when day_open<=3 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzcza,"
                           "round(min(case when day_open<=3 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abzczb,"
                           "round(min(case when day_open<=3 and pay_result =1 then amt else null end), 2) as t01abzczc,"
                           "round(min(case when day_open<=3 then amt else null end), 2) as t01abzczz,"
                           "round(min(case when day_open<=4 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzdaa,"
                           "round(min(case when day_open<=4 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abzdab,"
                           "round(min(case when day_open<=4 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abzdac,"
                           "round(min(case when day_open<=4 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abzdaz,"
                           "round(min(case when day_open<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzdba,"
                           "round(min(case when day_open<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abzdbb,"
                           "round(min(case when day_open<=4 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abzdbc,"
                           "round(min(case when day_open<=4 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abzdbz,"
                           "round(min(case when day_open<=4 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzdza,"
                           "round(min(case when day_open<=4 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abzdzb,"
                           "round(min(case when day_open<=4 and pay_result =1 then amt else null end), 2) as t01abzdzc,"
                           "round(min(case when day_open<=4 then amt else null end), 2) as t01abzdzz,"
                           "round(min(case when day_open<=5 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzeaa,"
                           "round(min(case when day_open<=5 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abzeab,"
                           "round(min(case when day_open<=5 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abzeac,"
                           "round(min(case when day_open<=5 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abzeaz,"
                           "round(min(case when day_open<=5 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzeba,"
                           "round(min(case when day_open<=5 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abzebb,"
                           "round(min(case when day_open<=5 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abzebc,"
                           "round(min(case when day_open<=5 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abzebz,"
                           "round(min(case when day_open<=5 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzeza,"
                           "round(min(case when day_open<=5 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abzezb,"
                           "round(min(case when day_open<=5 and pay_result =1 then amt else null end), 2) as t01abzezc,"
                           "round(min(case when day_open<=5 then amt else null end), 2) as t01abzezz,"
                           "round(min(case when day_open<=6 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzfaa,"
                           "round(min(case when day_open<=6 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abzfab,"
                           "round(min(case when day_open<=6 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abzfac,"
                           "round(min(case when day_open<=6 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abzfaz,"
                           "round(min(case when day_open<=6 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzfba,"
                           "round(min(case when day_open<=6 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abzfbb,"
                           "round(min(case when day_open<=6 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abzfbc,"
                           "round(min(case when day_open<=6 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abzfbz,"
                           "round(min(case when day_open<=6 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzfza,"
                           "round(min(case when day_open<=6 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abzfzb,"
                           "round(min(case when day_open<=6 and pay_result =1 then amt else null end), 2) as t01abzfzc,"
                           "round(min(case when day_open<=6 then amt else null end), 2) as t01abzfzz,"
                           "round(min(case when day_open<=7 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzgaa,"
                           "round(min(case when day_open<=7 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abzgab,"
                           "round(min(case when day_open<=7 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abzgac,"
                           "round(min(case when day_open<=7 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abzgaz,"
                           "round(min(case when day_open<=7 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzgba,"
                           "round(min(case when day_open<=7 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abzgbb,"
                           "round(min(case when day_open<=7 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abzgbc,"
                           "round(min(case when day_open<=7 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abzgbz,"
                           "round(min(case when day_open<=7 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzgza,"
                           "round(min(case when day_open<=7 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abzgzb,"
                           "round(min(case when day_open<=7 and pay_result =1 then amt else null end), 2) as t01abzgzc,"
                           "round(min(case when day_open<=7 then amt else null end), 2) as t01abzgzz,"
                           "round(min(case when day_open<=8 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzhaa,"
                           "round(min(case when day_open<=8 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abzhab,"
                           "round(min(case when day_open<=8 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abzhac,"
                           "round(min(case when day_open<=8 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abzhaz,"
                           "round(min(case when day_open<=8 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzhba,"
                           "round(min(case when day_open<=8 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abzhbb,"
                           "round(min(case when day_open<=8 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abzhbc,"
                           "round(min(case when day_open<=8 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abzhbz,"
                           "round(min(case when day_open<=8 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzhza,"
                           "round(min(case when day_open<=8 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abzhzb,"
                           "round(min(case when day_open<=8 and pay_result =1 then amt else null end), 2) as t01abzhzc,"
                           "round(min(case when day_open<=8 then amt else null end), 2) as t01abzhzz "
                           "from personal_cfsl_loan_deduct_seq_min_mid yy group by yy.idcard,yy.recall_date")




keys = minsqlDf.rdd.map(lambda row: dropFrame(row))
keys.repartition(10).saveAsTextFile(output_feature_path_pre + output_path + '/' + key_cal)
sc.stop()

print key_cal + "_sql_daily" + " success " + str(time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()))  +  "*"*90

