# encoding:utf-8 
t01_sql="""
round(max(case when day_pay<=1 and pay_result =1 then amt else null end), 2) as t01aaazzc,
round(max(case when day_pay<=1 then amt else null end), 2) as t01aaazzz,
round(max(case when day_pay<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aabzba,
round(max(case when day_pay<=2 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aabzbc,
round(max(case when day_pay<=2 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aabzbz,
round(max(case when day_pay<=2 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aabzza,
round(max(case when day_pay<=2 and pay_result =1 then amt else null end), 2) as t01aabzzc,
round(max(case when day_pay<=2 then amt else null end), 2) as t01aabzzz,
round(max(case when day_pay<=3 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aaczaz,
round(max(case when day_pay<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aaczba,
round(max(case when day_pay<=3 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aaczbc,
round(max(case when day_pay<=3 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aaczbz,
round(max(case when day_pay<=3 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aaczza,
round(max(case when day_pay<=3 and pay_result =1 then amt else null end), 2) as t01aaczzc,
round(max(case when day_pay<=3 then amt else null end), 2) as t01aaczzz,
round(max(case when day_pay<=4 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aadzac,
round(max(case when day_pay<=4 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aadzaz,
round(max(case when day_pay<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aadzba,
round(max(case when day_pay<=4 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aadzbc,
round(max(case when day_pay<=4 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aadzbz,
round(max(case when day_pay<=4 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aadzza,
round(max(case when day_pay<=4 and pay_result =1 then amt else null end), 2) as t01aadzzc,
round(max(case when day_pay<=4 then amt else null end), 2) as t01aadzzz,
round(max(case when day_pay<=5 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aaezaa,
round(max(case when day_pay<=5 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aaezac,
round(max(case when day_pay<=5 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aaezaz,
round(max(case when day_pay<=5 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aaezba,
round(max(case when day_pay<=5 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aaezbc,
round(max(case when day_pay<=5 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aaezbz,
round(max(case when day_pay<=5 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aaezza,
round(max(case when day_pay<=5 and pay_result =1 then amt else null end), 2) as t01aaezzc,
round(max(case when day_pay<=5 then amt else null end), 2) as t01aaezzz,
round(max(case when day_pay<=6 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aafzaa,
round(max(case when day_pay<=6 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aafzac,
round(max(case when day_pay<=6 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aafzaz,
round(max(case when day_pay<=6 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aafzba,
round(max(case when day_pay<=6 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aafzbc,
round(max(case when day_pay<=6 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aafzbz,
round(max(case when day_pay<=6 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aafzza,
round(max(case when day_pay<=6 and pay_result =1 then amt else null end), 2) as t01aafzzc,
round(max(case when day_pay<=6 then amt else null end), 2) as t01aafzzz,
round(max(case when day_pay<=7 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aagzaa,
round(max(case when day_pay<=7 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aagzac,
round(max(case when day_pay<=7 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aagzaz,
round(max(case when day_pay<=7 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aagzba,
round(max(case when day_pay<=7 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aagzbc,
round(max(case when day_pay<=7 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aagzbz,
round(max(case when day_pay<=7 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aagzza,
round(max(case when day_pay<=7 and pay_result =1 then amt else null end), 2) as t01aagzzc,
round(max(case when day_pay<=7 then amt else null end), 2) as t01aagzzz,
round(max(case when day_pay<=8 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aahzaa,
round(max(case when day_pay<=8 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aahzac,
round(max(case when day_pay<=8 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aahzaz,
round(max(case when day_pay<=8 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aahzba,
round(max(case when day_pay<=8 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aahzbc,
round(max(case when day_pay<=8 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aahzbz,
round(max(case when day_pay<=8 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aahzza,
round(max(case when day_pay<=8 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aahzzb,
round(max(case when day_pay<=8 and pay_result =1 then amt else null end), 2) as t01aahzzc,
round(max(case when day_pay<=8 then amt else null end), 2) as t01aahzzz,
round(max(case when row_num<=1 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aaizaa,
round(max(case when row_num<=1 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aaizac,
round(max(case when row_num<=1 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aaizaz,
round(max(case when row_num<=1 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aaizba,
round(max(case when row_num<=1 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aaizbc,
round(max(case when row_num<=1 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aaizbz,
round(max(case when row_num<=1 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aaizza,
round(max(case when row_num<=1 and pay_result =1 then amt else null end), 2) as t01aaizzc,
round(max(case when row_num<=1 then amt else null end), 2) as t01aaizzz,
round(max(case when row_num<=2 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aajzaa,
round(max(case when row_num<=2 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aajzac,
round(max(case when row_num<=2 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aajzaz,
round(max(case when row_num<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aajzba,
round(max(case when row_num<=2 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aajzbc,
round(max(case when row_num<=2 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aajzbz,
round(max(case when row_num<=2 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aajzza,
round(max(case when row_num<=2 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aajzzb,
round(max(case when row_num<=2 and pay_result =1 then amt else null end), 2) as t01aajzzc,
round(max(case when row_num<=2 then amt else null end), 2) as t01aajzzz,
round(max(case when row_num<=3 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aakzaa,
round(max(case when row_num<=3 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aakzac,
round(max(case when row_num<=3 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aakzaz,
round(max(case when row_num<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aakzba,
round(max(case when row_num<=3 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aakzbc,
round(max(case when row_num<=3 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aakzbz,
round(max(case when row_num<=3 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aakzza,
round(max(case when row_num<=3 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aakzzb,
round(max(case when row_num<=3 and pay_result =1 then amt else null end), 2) as t01aakzzc,
round(max(case when row_num<=3 then amt else null end), 2) as t01aakzzz,
round(max(case when row_num<=4 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aalzaa,
round(max(case when row_num<=4 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aalzac,
round(max(case when row_num<=4 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aalzaz,
round(max(case when row_num<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aalzba,
round(max(case when row_num<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aalzbb,
round(max(case when row_num<=4 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aalzbc,
round(max(case when row_num<=4 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aalzbz,
round(max(case when row_num<=4 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aalzza,
round(max(case when row_num<=4 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aalzzb,
round(max(case when row_num<=4 and pay_result =1 then amt else null end), 2) as t01aalzzc,
round(max(case when row_num<=4 then amt else null end), 2) as t01aalzzz,
round(max(case when goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazzaa,
round(max(case when goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aazzac,
round(max(case when goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aazzaz,
round(max(case when goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazzba,
round(max(case when goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aazzbb,
round(max(case when goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aazzbc,
round(max(case when goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aazzbz,
round(max(case when pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazzza,
round(max(case when pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aazzzb,
round(max(case when pay_result =1 then amt else null end), 2) as t01aazzzc,
round(max(amt), 2) as t01aazzzz,
round(max(case when goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then day_pay else null end)) as t01bazzaa,
round(max(case when goods_if_subbizcatname = 'cf' and pay_result =1 then day_pay else null end)) as t01bazzac,
round(max(case when goods_if_subbizcatname = 'cf' then day_pay else null end)) as t01bazzaz,
round(max(case when goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then day_pay else null end)) as t01bazzba,
round(max(case when goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then day_pay else null end)) as t01bazzbb,
round(max(case when goods_if_subbizcatname ='sl' and pay_result =1 then day_pay else null end)) as t01bazzbc,
round(max(case when goods_if_subbizcatname ='sl' then day_pay else null end)) as t01bazzbz,
round(max(case when pay_result =0 and req_if_trademsg = 1 then day_pay else null end)) as t01bazzza,
round(max(case when pay_result =0 and req_if_trademsg = 2 then day_pay else null end)) as t01bazzzb,
round(max(case when pay_result =1 then day_pay else null end)) as t01bazzzc,
round(max(day_pay)) as t01bazzzz,
round(max(case when day_open<=3 then amt else null end), 2) as t01aazczz,
round(max(case when day_open<=4 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aazdbc,
round(max(case when day_open<=4 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aazdbz,
round(max(case when day_open<=4 and pay_result =1 then amt else null end), 2) as t01aazdzc,
round(max(case when day_open<=4 then amt else null end), 2) as t01aazdzz,
round(max(case when day_open<=5 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aazebc,
round(max(case when day_open<=5 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aazebz,
round(max(case when day_open<=5 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazeza,
round(max(case when day_open<=5 and pay_result =1 then amt else null end), 2) as t01aazezc,
round(max(case when day_open<=5 then amt else null end), 2) as t01aazezz,
round(max(case when day_open<=6 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aazfac,
round(max(case when day_open<=6 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aazfaz,
round(max(case when day_open<=6 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazfba,
round(max(case when day_open<=6 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aazfbc,
round(max(case when day_open<=6 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aazfbz,
round(max(case when day_open<=6 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazfza,
round(max(case when day_open<=6 and pay_result =1 then amt else null end), 2) as t01aazfzc,
round(max(case when day_open<=6 then amt else null end), 2) as t01aazfzz,
round(max(case when day_open<=7 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazgaa,
round(max(case when day_open<=7 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aazgac,
round(max(case when day_open<=7 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aazgaz,
round(max(case when day_open<=7 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazgba,
round(max(case when day_open<=7 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aazgbc,
round(max(case when day_open<=7 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aazgbz,
round(max(case when day_open<=7 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazgza,
round(max(case when day_open<=7 and pay_result =1 then amt else null end), 2) as t01aazgzc,
round(max(case when day_open<=7 then amt else null end), 2) as t01aazgzz,
round(max(case when day_open<=8 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazhaa,
round(max(case when day_open<=8 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aazhac,
round(max(case when day_open<=8 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aazhaz,
round(max(case when day_open<=8 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazhba,
round(max(case when day_open<=8 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aazhbc,
round(max(case when day_open<=8 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aazhbz,
round(max(case when day_open<=8 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aazhza,
round(max(case when day_open<=8 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aazhzb,
round(max(case when day_open<=8 and pay_result =1 then amt else null end), 2) as t01aazhzc,
round(max(case when day_open<=8 then amt else null end), 2) as t01aazhzz,
round(min(case when day_pay<=1 and pay_result =1 then amt else null end), 2) as t01abazzc,
round(min(case when day_pay<=1 then amt else null end), 2) as t01abazzz,
round(min(case when day_pay<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abbzba,
round(min(case when day_pay<=2 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abbzbc,
round(min(case when day_pay<=2 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abbzbz,
round(min(case when day_pay<=2 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abbzza,
round(min(case when day_pay<=2 and pay_result =1 then amt else null end), 2) as t01abbzzc,
round(min(case when day_pay<=2 then amt else null end), 2) as t01abbzzz,
round(min(case when day_pay<=3 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abczaz,
round(min(case when day_pay<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abczba,
round(min(case when day_pay<=3 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abczbc,
round(min(case when day_pay<=3 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abczbz,
round(min(case when day_pay<=3 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abczza,
round(min(case when day_pay<=3 and pay_result =1 then amt else null end), 2) as t01abczzc,
round(min(case when day_pay<=3 then amt else null end), 2) as t01abczzz,
round(min(case when day_pay<=4 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abdzac,
round(min(case when day_pay<=4 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abdzaz,
round(min(case when day_pay<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abdzba,
round(min(case when day_pay<=4 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abdzbc,
round(min(case when day_pay<=4 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abdzbz,
round(min(case when day_pay<=4 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abdzza,
round(min(case when day_pay<=4 and pay_result =1 then amt else null end), 2) as t01abdzzc,
round(min(case when day_pay<=4 then amt else null end), 2) as t01abdzzz,
round(min(case when day_pay<=5 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abezaa,
round(min(case when day_pay<=5 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abezac,
round(min(case when day_pay<=5 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abezaz,
round(min(case when day_pay<=5 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abezba,
round(min(case when day_pay<=5 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abezbc,
round(min(case when day_pay<=5 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abezbz,
round(min(case when day_pay<=5 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abezza,
round(min(case when day_pay<=5 and pay_result =1 then amt else null end), 2) as t01abezzc,
round(min(case when day_pay<=5 then amt else null end), 2) as t01abezzz,
round(min(case when day_pay<=6 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abfzaa,
round(min(case when day_pay<=6 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abfzac,
round(min(case when day_pay<=6 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abfzaz,
round(min(case when day_pay<=6 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abfzba,
round(min(case when day_pay<=6 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abfzbc,
round(min(case when day_pay<=6 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abfzbz,
round(min(case when day_pay<=6 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abfzza,
round(min(case when day_pay<=6 and pay_result =1 then amt else null end), 2) as t01abfzzc,
round(min(case when day_pay<=6 then amt else null end), 2) as t01abfzzz,
round(min(case when day_pay<=7 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abgzaa,
round(min(case when day_pay<=7 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abgzac,
round(min(case when day_pay<=7 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abgzaz,
round(min(case when day_pay<=7 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abgzba,
round(min(case when day_pay<=7 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abgzbc,
round(min(case when day_pay<=7 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abgzbz,
round(min(case when day_pay<=7 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abgzza,
round(min(case when day_pay<=7 and pay_result =1 then amt else null end), 2) as t01abgzzc,
round(min(case when day_pay<=7 then amt else null end), 2) as t01abgzzz,
round(min(case when day_pay<=8 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abhzaa,
round(min(case when day_pay<=8 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abhzac,
round(min(case when day_pay<=8 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abhzaz,
round(min(case when day_pay<=8 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abhzba,
round(min(case when day_pay<=8 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abhzbc,
round(min(case when day_pay<=8 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abhzbz,
round(min(case when day_pay<=8 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abhzza,
round(min(case when day_pay<=8 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abhzzb,
round(min(case when day_pay<=8 and pay_result =1 then amt else null end), 2) as t01abhzzc,
round(min(case when day_pay<=8 then amt else null end), 2) as t01abhzzz,
round(min(case when row_num<=1 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abizaa,
round(min(case when row_num<=1 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abizac,
round(min(case when row_num<=1 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abizaz,
round(min(case when row_num<=1 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abizba,
round(min(case when row_num<=1 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abizbc,
round(min(case when row_num<=1 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abizbz,
round(min(case when row_num<=1 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abizza,
round(min(case when row_num<=1 and pay_result =1 then amt else null end), 2) as t01abizzc,
round(min(case when row_num<=1 then amt else null end), 2) as t01abizzz,
round(min(case when row_num<=2 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abjzaa,
round(min(case when row_num<=2 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abjzac,
round(min(case when row_num<=2 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abjzaz,
round(min(case when row_num<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abjzba,
round(min(case when row_num<=2 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abjzbc,
round(min(case when row_num<=2 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abjzbz,
round(min(case when row_num<=2 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abjzza,
round(min(case when row_num<=2 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abjzzb,
round(min(case when row_num<=2 and pay_result =1 then amt else null end), 2) as t01abjzzc,
round(min(case when row_num<=2 then amt else null end), 2) as t01abjzzz,
round(min(case when row_num<=3 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abkzaa,
round(min(case when row_num<=3 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abkzac,
round(min(case when row_num<=3 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abkzaz,
round(min(case when row_num<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abkzba,
round(min(case when row_num<=3 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abkzbc,
round(min(case when row_num<=3 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abkzbz,
round(min(case when row_num<=3 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abkzza,
round(min(case when row_num<=3 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abkzzb,
round(min(case when row_num<=3 and pay_result =1 then amt else null end), 2) as t01abkzzc,
round(min(case when row_num<=3 then amt else null end), 2) as t01abkzzz,
round(min(case when row_num<=4 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01ablzaa,
round(min(case when row_num<=4 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01ablzac,
round(min(case when row_num<=4 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01ablzaz,
round(min(case when row_num<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01ablzba,
round(min(case when row_num<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01ablzbb,
round(min(case when row_num<=4 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01ablzbc,
round(min(case when row_num<=4 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01ablzbz,
round(min(case when row_num<=4 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01ablzza,
round(min(case when row_num<=4 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01ablzzb,
round(min(case when row_num<=4 and pay_result =1 then amt else null end), 2) as t01ablzzc,
round(min(case when row_num<=4 then amt else null end), 2) as t01ablzzz,
round(min(case when goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzzaa,
round(min(case when goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abzzac,
round(min(case when goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abzzaz,
round(min(case when goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzzba,
round(min(case when goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abzzbb,
round(min(case when goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abzzbc,
round(min(case when goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abzzbz,
round(min(case when pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzzza,
round(min(case when pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abzzzb,
round(min(case when pay_result =1 then amt else null end), 2) as t01abzzzc,
round(min(amt)) as t01abzzzz,
round(min(case when goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then day_pay else null end)) as t01bbzzaa,
round(min(case when goods_if_subbizcatname = 'cf' and pay_result =1 then day_pay else null end)) as t01bbzzac,
round(min(case when goods_if_subbizcatname = 'cf' then day_pay else null end)) as t01bbzzaz,
round(min(case when goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then day_pay else null end)) as t01bbzzba,
round(min(case when goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then day_pay else null end)) as t01bbzzbb,
round(min(case when goods_if_subbizcatname ='sl' and pay_result =1 then day_pay else null end)) as t01bbzzbc,
round(min(case when goods_if_subbizcatname ='sl' then day_pay else null end)) as t01bbzzbz,
round(min(case when pay_result =0 and req_if_trademsg = 1 then day_pay else null end)) as t01bbzzza,
round(min(case when pay_result =0 and req_if_trademsg = 2 then day_pay else null end)) as t01bbzzzb,
round(min(case when pay_result =1 then day_pay else null end)) as t01bbzzzc,
round(min(day_pay)) as t01bbzzzz,
round(min(case when day_open<=3 then amt else null end), 2) as t01abzczz,
round(min(case when day_open<=4 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abzdbc,
round(min(case when day_open<=4 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abzdbz,
round(min(case when day_open<=4 and pay_result =1 then amt else null end), 2) as t01abzdzc,
round(min(case when day_open<=4 then amt else null end), 2) as t01abzdzz,
round(min(case when day_open<=5 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abzebc,
round(min(case when day_open<=5 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abzebz,
round(min(case when day_open<=5 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzeza,
round(min(case when day_open<=5 and pay_result =1 then amt else null end), 2) as t01abzezc,
round(min(case when day_open<=5 then amt else null end), 2) as t01abzezz,
round(min(case when day_open<=6 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abzfac,
round(min(case when day_open<=6 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abzfaz,
round(min(case when day_open<=6 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzfba,
round(min(case when day_open<=6 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abzfbc,
round(min(case when day_open<=6 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abzfbz,
round(min(case when day_open<=6 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzfza,
round(min(case when day_open<=6 and pay_result =1 then amt else null end), 2) as t01abzfzc,
round(min(case when day_open<=6 then amt else null end), 2) as t01abzfzz,
round(min(case when day_open<=7 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzgaa,
round(min(case when day_open<=7 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abzgac,
round(min(case when day_open<=7 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abzgaz,
round(min(case when day_open<=7 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzgba,
round(min(case when day_open<=7 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abzgbc,
round(min(case when day_open<=7 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abzgbz,
round(min(case when day_open<=7 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzgza,
round(min(case when day_open<=7 and pay_result =1 then amt else null end), 2) as t01abzgzc,
round(min(case when day_open<=7 then amt else null end), 2) as t01abzgzz,
round(min(case when day_open<=8 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzhaa,
round(min(case when day_open<=8 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01abzhac,
round(min(case when day_open<=8 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01abzhaz,
round(min(case when day_open<=8 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzhba,
round(min(case when day_open<=8 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01abzhbc,
round(min(case when day_open<=8 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01abzhbz,
round(min(case when day_open<=8 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01abzhza,
round(min(case when day_open<=8 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01abzhzb,
round(min(case when day_open<=8 and pay_result =1 then amt else null end), 2) as t01abzhzc,
round(min(case when day_open<=8 then amt else null end), 2) as t01abzhzz,
round(sum(case when day_pay<=1 and pay_result =1 then amt else null end), 2) as t01acazzc,
round(sum(case when day_pay<=1 then amt else null end), 2) as t01acazzz,
round(sum(case when day_pay<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01acbzba,
round(sum(case when day_pay<=2 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01acbzbc,
round(sum(case when day_pay<=2 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01acbzbz,
round(sum(case when day_pay<=2 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01acbzza,
round(sum(case when day_pay<=2 and pay_result =1 then amt else null end), 2) as t01acbzzc,
round(sum(case when day_pay<=2 then amt else null end), 2) as t01acbzzz,
round(sum(case when day_pay<=3 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01acczaz,
round(sum(case when day_pay<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01acczba,
round(sum(case when day_pay<=3 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01acczbc,
round(sum(case when day_pay<=3 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01acczbz,
round(sum(case when day_pay<=3 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01acczza,
round(sum(case when day_pay<=3 and pay_result =1 then amt else null end), 2) as t01acczzc,
round(sum(case when day_pay<=3 then amt else null end), 2) as t01acczzz,
round(sum(case when day_pay<=4 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01acdzac,
round(sum(case when day_pay<=4 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01acdzaz,
round(sum(case when day_pay<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01acdzba,
round(sum(case when day_pay<=4 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01acdzbc,
round(sum(case when day_pay<=4 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01acdzbz,
round(sum(case when day_pay<=4 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01acdzza,
round(sum(case when day_pay<=4 and pay_result =1 then amt else null end), 2) as t01acdzzc,
round(sum(case when day_pay<=4 then amt else null end), 2) as t01acdzzz,
round(sum(case when day_pay<=5 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01acezaa,
round(sum(case when day_pay<=5 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01acezac,
round(sum(case when day_pay<=5 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01acezaz,
round(sum(case when day_pay<=5 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01acezba,
round(sum(case when day_pay<=5 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01acezbc,
round(sum(case when day_pay<=5 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01acezbz,
round(sum(case when day_pay<=5 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01acezza,
round(sum(case when day_pay<=5 and pay_result =1 then amt else null end), 2) as t01acezzc,
round(sum(case when day_pay<=5 then amt else null end), 2) as t01acezzz,
round(sum(case when day_pay<=6 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01acfzaa,
round(sum(case when day_pay<=6 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01acfzac,
round(sum(case when day_pay<=6 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01acfzaz,
round(sum(case when day_pay<=6 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01acfzba,
round(sum(case when day_pay<=6 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01acfzbc,
round(sum(case when day_pay<=6 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01acfzbz,
round(sum(case when day_pay<=6 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01acfzza,
round(sum(case when day_pay<=6 and pay_result =1 then amt else null end), 2) as t01acfzzc,
round(sum(case when day_pay<=6 then amt else null end), 2) as t01acfzzz,
round(sum(case when day_pay<=7 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01acgzaa,
round(sum(case when day_pay<=7 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01acgzac,
round(sum(case when day_pay<=7 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01acgzaz,
round(sum(case when day_pay<=7 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01acgzba,
round(sum(case when day_pay<=7 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01acgzbc,
round(sum(case when day_pay<=7 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01acgzbz,
round(sum(case when day_pay<=7 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01acgzza,
round(sum(case when day_pay<=7 and pay_result =1 then amt else null end), 2) as t01acgzzc,
round(sum(case when day_pay<=7 then amt else null end), 2) as t01acgzzz,
round(sum(case when day_pay<=8 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01achzaa,
round(sum(case when day_pay<=8 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01achzac,
round(sum(case when day_pay<=8 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01achzaz,
round(sum(case when day_pay<=8 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01achzba,
round(sum(case when day_pay<=8 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01achzbc,
round(sum(case when day_pay<=8 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01achzbz,
round(sum(case when day_pay<=8 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01achzza,
round(sum(case when day_pay<=8 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01achzzb,
round(sum(case when day_pay<=8 and pay_result =1 then amt else null end), 2) as t01achzzc,
round(sum(case when day_pay<=8 then amt else null end), 2) as t01achzzz,
round(sum(case when row_num<=1 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01acizaa,
round(sum(case when row_num<=1 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01acizac,
round(sum(case when row_num<=1 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01acizaz,
round(sum(case when row_num<=1 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01acizba,
round(sum(case when row_num<=1 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01acizbc,
round(sum(case when row_num<=1 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01acizbz,
round(sum(case when row_num<=1 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01acizza,
round(sum(case when row_num<=1 and pay_result =1 then amt else null end), 2) as t01acizzc,
round(sum(case when row_num<=1 then amt else null end), 2) as t01acizzz,
round(sum(case when row_num<=2 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01acjzaa,
round(sum(case when row_num<=2 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01acjzac,
round(sum(case when row_num<=2 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01acjzaz,
round(sum(case when row_num<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01acjzba,
round(sum(case when row_num<=2 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01acjzbc,
round(sum(case when row_num<=2 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01acjzbz,
round(sum(case when row_num<=2 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01acjzza,
round(sum(case when row_num<=2 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01acjzzb,
round(sum(case when row_num<=2 and pay_result =1 then amt else null end), 2) as t01acjzzc,
round(sum(case when row_num<=2 then amt else null end), 2) as t01acjzzz,
round(sum(case when row_num<=3 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01ackzaa,
round(sum(case when row_num<=3 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01ackzac,
round(sum(case when row_num<=3 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01ackzaz,
round(sum(case when row_num<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01ackzba,
round(sum(case when row_num<=3 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01ackzbc,
round(sum(case when row_num<=3 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01ackzbz,
round(sum(case when row_num<=3 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01ackzza,
round(sum(case when row_num<=3 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01ackzzb,
round(sum(case when row_num<=3 and pay_result =1 then amt else null end), 2) as t01ackzzc,
round(sum(case when row_num<=3 then amt else null end), 2) as t01ackzzz,
round(sum(case when row_num<=4 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aclzaa,
round(sum(case when row_num<=4 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aclzac,
round(sum(case when row_num<=4 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aclzaz,
round(sum(case when row_num<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aclzba,
round(sum(case when row_num<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aclzbb,
round(sum(case when row_num<=4 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aclzbc,
round(sum(case when row_num<=4 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aclzbz,
round(sum(case when row_num<=4 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aclzza,
round(sum(case when row_num<=4 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aclzzb,
round(sum(case when row_num<=4 and pay_result =1 then amt else null end), 2) as t01aclzzc,
round(sum(case when row_num<=4 then amt else null end), 2) as t01aclzzz,
round(sum(case when goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aczzaa,
round(sum(case when goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aczzac,
round(sum(case when goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aczzaz,
round(sum(case when goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aczzba,
round(sum(case when goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aczzbb,
round(sum(case when goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aczzbc,
round(sum(case when goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aczzbz,
round(sum(case when pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aczzza,
round(sum(case when pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aczzzb,
round(sum(case when pay_result =1 then amt else null end), 2) as t01aczzzc,
round(sum(amt), 2) as t01aczzzz,
round(sum(case when day_pay<=1 and pay_result =1 then count_num else null end)) as t01ccazzc,
round(sum(case when day_pay<=1 then count_num else null end)) as t01ccazzz,
round(sum(case when day_pay<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01ccbzba,
round(sum(case when day_pay<=2 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else null end)) as t01ccbzbc,
round(sum(case when day_pay<=2 and goods_if_subbizcatname ='sl' then count_num else null end)) as t01ccbzbz,
round(sum(case when day_pay<=2 and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01ccbzza,
round(sum(case when day_pay<=2 and pay_result =1 then count_num else null end)) as t01ccbzzc,
round(sum(case when day_pay<=2 then count_num else null end)) as t01ccbzzz,
round(sum(case when day_pay<=3 and goods_if_subbizcatname = 'cf' then count_num else null end)) as t01ccczaz,
round(sum(case when day_pay<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01ccczba,
round(sum(case when day_pay<=3 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else null end)) as t01ccczbc,
round(sum(case when day_pay<=3 and goods_if_subbizcatname ='sl' then count_num else null end)) as t01ccczbz,
round(sum(case when day_pay<=3 and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01ccczza,
round(sum(case when day_pay<=3 and pay_result =1 then count_num else null end)) as t01ccczzc,
round(sum(case when day_pay<=3 then count_num else null end)) as t01ccczzz,
round(sum(case when day_pay<=4 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else null end)) as t01ccdzac,
round(sum(case when day_pay<=4 and goods_if_subbizcatname = 'cf' then count_num else null end)) as t01ccdzaz,
round(sum(case when day_pay<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01ccdzba,
round(sum(case when day_pay<=4 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else null end)) as t01ccdzbc,
round(sum(case when day_pay<=4 and goods_if_subbizcatname ='sl' then count_num else null end)) as t01ccdzbz,
round(sum(case when day_pay<=4 and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01ccdzza,
round(sum(case when day_pay<=4 and pay_result =1 then count_num else null end)) as t01ccdzzc,
round(sum(case when day_pay<=4 then count_num else null end)) as t01ccdzzz,
round(sum(case when day_pay<=5 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01ccezaa,
round(sum(case when day_pay<=5 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else null end)) as t01ccezac,
round(sum(case when day_pay<=5 and goods_if_subbizcatname = 'cf' then count_num else null end)) as t01ccezaz,
round(sum(case when day_pay<=5 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01ccezba,
round(sum(case when day_pay<=5 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else null end)) as t01ccezbc,
round(sum(case when day_pay<=5 and goods_if_subbizcatname ='sl' then count_num else null end)) as t01ccezbz,
round(sum(case when day_pay<=5 and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01ccezza,
round(sum(case when day_pay<=5 and pay_result =1 then count_num else null end)) as t01ccezzc,
round(sum(case when day_pay<=5 then count_num else null end)) as t01ccezzz,
round(sum(case when day_pay<=6 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01ccfzaa,
round(sum(case when day_pay<=6 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else null end)) as t01ccfzac,
round(sum(case when day_pay<=6 and goods_if_subbizcatname = 'cf' then count_num else null end)) as t01ccfzaz,
round(sum(case when day_pay<=6 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01ccfzba,
round(sum(case when day_pay<=6 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else null end)) as t01ccfzbc,
round(sum(case when day_pay<=6 and goods_if_subbizcatname ='sl' then count_num else null end)) as t01ccfzbz,
round(sum(case when day_pay<=6 and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01ccfzza,
round(sum(case when day_pay<=6 and pay_result =1 then count_num else null end)) as t01ccfzzc,
round(sum(case when day_pay<=6 then count_num else null end)) as t01ccfzzz,
round(sum(case when day_pay<=7 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01ccgzaa,
round(sum(case when day_pay<=7 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else null end)) as t01ccgzac,
round(sum(case when day_pay<=7 and goods_if_subbizcatname = 'cf' then count_num else null end)) as t01ccgzaz,
round(sum(case when day_pay<=7 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01ccgzba,
round(sum(case when day_pay<=7 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else null end)) as t01ccgzbc,
round(sum(case when day_pay<=7 and goods_if_subbizcatname ='sl' then count_num else null end)) as t01ccgzbz,
round(sum(case when day_pay<=7 and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01ccgzza,
round(sum(case when day_pay<=7 and pay_result =1 then count_num else null end)) as t01ccgzzc,
round(sum(case when day_pay<=7 then count_num else null end)) as t01ccgzzz,
round(sum(case when day_pay<=8 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01cchzaa,
round(sum(case when day_pay<=8 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else null end)) as t01cchzac,
round(sum(case when day_pay<=8 and goods_if_subbizcatname = 'cf' then count_num else null end)) as t01cchzaz,
round(sum(case when day_pay<=8 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01cchzba,
round(sum(case when day_pay<=8 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else null end)) as t01cchzbc,
round(sum(case when day_pay<=8 and goods_if_subbizcatname ='sl' then count_num else null end)) as t01cchzbz,
round(sum(case when day_pay<=8 and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01cchzza,
round(sum(case when day_pay<=8 and pay_result =0 and req_if_trademsg = 2 then count_num else null end)) as t01cchzzb,
round(sum(case when day_pay<=8 and pay_result =1 then count_num else null end)) as t01cchzzc,
round(sum(case when day_pay<=8 then count_num else null end)) as t01cchzzz,
round(sum(case when row_num<=1 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01ccizaa,
round(sum(case when row_num<=1 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else null end)) as t01ccizac,
round(sum(case when row_num<=1 and goods_if_subbizcatname = 'cf' then count_num else null end)) as t01ccizaz,
round(sum(case when row_num<=1 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01ccizba,
round(sum(case when row_num<=1 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else null end)) as t01ccizbc,
round(sum(case when row_num<=1 and goods_if_subbizcatname ='sl' then count_num else null end)) as t01ccizbz,
round(sum(case when row_num<=1 and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01ccizza,
round(sum(case when row_num<=1 and pay_result =1 then count_num else null end)) as t01ccizzc,
round(sum(case when row_num<=1 then count_num else null end)) as t01ccizzz,
round(sum(case when row_num<=2 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01ccjzaa,
round(sum(case when row_num<=2 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else null end)) as t01ccjzac,
round(sum(case when row_num<=2 and goods_if_subbizcatname = 'cf' then count_num else null end)) as t01ccjzaz,
round(sum(case when row_num<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01ccjzba,
round(sum(case when row_num<=2 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else null end)) as t01ccjzbc,
round(sum(case when row_num<=2 and goods_if_subbizcatname ='sl' then count_num else null end)) as t01ccjzbz,
round(sum(case when row_num<=2 and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01ccjzza,
round(sum(case when row_num<=2 and pay_result =0 and req_if_trademsg = 2 then count_num else null end)) as t01ccjzzb,
round(sum(case when row_num<=2 and pay_result =1 then count_num else null end)) as t01ccjzzc,
round(sum(case when row_num<=2 then count_num else null end)) as t01ccjzzz,
round(sum(case when row_num<=3 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01cckzaa,
round(sum(case when row_num<=3 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else null end)) as t01cckzac,
round(sum(case when row_num<=3 and goods_if_subbizcatname = 'cf' then count_num else null end)) as t01cckzaz,
round(sum(case when row_num<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01cckzba,
round(sum(case when row_num<=3 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else null end)) as t01cckzbc,
round(sum(case when row_num<=3 and goods_if_subbizcatname ='sl' then count_num else null end)) as t01cckzbz,
round(sum(case when row_num<=3 and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01cckzza,
round(sum(case when row_num<=3 and pay_result =0 and req_if_trademsg = 2 then count_num else null end)) as t01cckzzb,
round(sum(case when row_num<=3 and pay_result =1 then count_num else null end)) as t01cckzzc,
round(sum(case when row_num<=3 then count_num else null end)) as t01cckzzz,
round(sum(case when row_num<=4 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01cclzaa,
round(sum(case when row_num<=4 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else null end)) as t01cclzac,
round(sum(case when row_num<=4 and goods_if_subbizcatname = 'cf' then count_num else null end)) as t01cclzaz,
round(sum(case when row_num<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01cclzba,
round(sum(case when row_num<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then count_num else null end)) as t01cclzbb,
round(sum(case when row_num<=4 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else null end)) as t01cclzbc,
round(sum(case when row_num<=4 and goods_if_subbizcatname ='sl' then count_num else null end)) as t01cclzbz,
round(sum(case when row_num<=4 and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01cclzza,
round(sum(case when row_num<=4 and pay_result =0 and req_if_trademsg = 2 then count_num else null end)) as t01cclzzb,
round(sum(case when row_num<=4 and pay_result =1 then count_num else null end)) as t01cclzzc,
round(sum(case when row_num<=4 then count_num else null end)) as t01cclzzz,
round(sum(case when goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01cczzaa,
round(sum(case when goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else null end)) as t01cczzac,
round(sum(case when goods_if_subbizcatname = 'cf' then count_num else null end)) as t01cczzaz,
round(sum(case when goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01cczzba,
round(sum(case when goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then count_num else null end)) as t01cczzbb,
round(sum(case when goods_if_subbizcatname ='sl' and pay_result =1 then count_num else null end)) as t01cczzbc,
round(sum(case when goods_if_subbizcatname ='sl' then count_num else null end)) as t01cczzbz,
round(sum(case when pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01cczzza,
round(sum(case when pay_result =0 and req_if_trademsg = 2 then count_num else null end)) as t01cczzzb,
round(sum(case when pay_result =1 then count_num else null end)) as t01cczzzc,
round(sum(count_num)) as t01cczzzz,
round(sum(case when day_open<=3 then amt else null end), 2) as t01aczczz,
round(sum(case when day_open<=4 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aczdbc,
round(sum(case when day_open<=4 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aczdbz,
round(sum(case when day_open<=4 and pay_result =1 then amt else null end), 2) as t01aczdzc,
round(sum(case when day_open<=4 then amt else null end), 2) as t01aczdzz,
round(sum(case when day_open<=5 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aczebc,
round(sum(case when day_open<=5 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aczebz,
round(sum(case when day_open<=5 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aczeza,
round(sum(case when day_open<=5 and pay_result =1 then amt else null end), 2) as t01aczezc,
round(sum(case when day_open<=5 then amt else null end), 2) as t01aczezz,
round(sum(case when day_open<=6 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aczfac,
round(sum(case when day_open<=6 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aczfaz,
round(sum(case when day_open<=6 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aczfba,
round(sum(case when day_open<=6 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aczfbc,
round(sum(case when day_open<=6 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aczfbz,
round(sum(case when day_open<=6 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aczfza,
round(sum(case when day_open<=6 and pay_result =1 then amt else null end), 2) as t01aczfzc,
round(sum(case when day_open<=6 then amt else null end), 2) as t01aczfzz,
round(sum(case when day_open<=7 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aczgaa,
round(sum(case when day_open<=7 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aczgac,
round(sum(case when day_open<=7 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aczgaz,
round(sum(case when day_open<=7 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aczgba,
round(sum(case when day_open<=7 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aczgbc,
round(sum(case when day_open<=7 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aczgbz,
round(sum(case when day_open<=7 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aczgza,
round(sum(case when day_open<=7 and pay_result =1 then amt else null end), 2) as t01aczgzc,
round(sum(case when day_open<=7 then amt else null end), 2) as t01aczgzz,
round(sum(case when day_open<=8 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aczhaa,
round(sum(case when day_open<=8 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else null end), 2) as t01aczhac,
round(sum(case when day_open<=8 and goods_if_subbizcatname = 'cf' then amt else null end), 2) as t01aczhaz,
round(sum(case when day_open<=8 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aczhba,
round(sum(case when day_open<=8 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else null end), 2) as t01aczhbc,
round(sum(case when day_open<=8 and goods_if_subbizcatname ='sl' then amt else null end), 2) as t01aczhbz,
round(sum(case when day_open<=8 and pay_result =0 and req_if_trademsg = 1 then amt else null end), 2) as t01aczhza,
round(sum(case when day_open<=8 and pay_result =0 and req_if_trademsg = 2 then amt else null end), 2) as t01aczhzb,
round(sum(case when day_open<=8 and pay_result =1 then amt else null end), 2) as t01aczhzc,
round(sum(case when day_open<=8 then amt else null end), 2) as t01aczhzz,
round(sum(case when day_open<=3 then count_num else null end)) as t01cczczz,
round(sum(case when day_open<=4 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else null end)) as t01cczdbc,
round(sum(case when day_open<=4 and goods_if_subbizcatname ='sl' then count_num else null end)) as t01cczdbz,
round(sum(case when day_open<=4 and pay_result =1 then count_num else null end)) as t01cczdzc,
round(sum(case when day_open<=4 then count_num else null end)) as t01cczdzz,
round(sum(case when day_open<=5 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else null end)) as t01cczebc,
round(sum(case when day_open<=5 and goods_if_subbizcatname ='sl' then count_num else null end)) as t01cczebz,
round(sum(case when day_open<=5 and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01cczeza,
round(sum(case when day_open<=5 and pay_result =1 then count_num else null end)) as t01cczezc,
round(sum(case when day_open<=5 then count_num else null end)) as t01cczezz,
round(sum(case when day_open<=6 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else null end)) as t01cczfac,
round(sum(case when day_open<=6 and goods_if_subbizcatname = 'cf' then count_num else null end)) as t01cczfaz,
round(sum(case when day_open<=6 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01cczfba,
round(sum(case when day_open<=6 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else null end)) as t01cczfbc,
round(sum(case when day_open<=6 and goods_if_subbizcatname ='sl' then count_num else null end)) as t01cczfbz,
round(sum(case when day_open<=6 and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01cczfza,
round(sum(case when day_open<=6 and pay_result =1 then count_num else null end)) as t01cczfzc,
round(sum(case when day_open<=6 then count_num else null end)) as t01cczfzz,
round(sum(case when day_open<=7 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01cczgaa,
round(sum(case when day_open<=7 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else null end)) as t01cczgac,
round(sum(case when day_open<=7 and goods_if_subbizcatname = 'cf' then count_num else null end)) as t01cczgaz,
round(sum(case when day_open<=7 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01cczgba,
round(sum(case when day_open<=7 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else null end)) as t01cczgbc,
round(sum(case when day_open<=7 and goods_if_subbizcatname ='sl' then count_num else null end)) as t01cczgbz,
round(sum(case when day_open<=7 and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01cczgza,
round(sum(case when day_open<=7 and pay_result =1 then count_num else null end)) as t01cczgzc,
round(sum(case when day_open<=7 then count_num else null end)) as t01cczgzz,
round(sum(case when day_open<=8 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01cczhaa,
round(sum(case when day_open<=8 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else null end)) as t01cczhac,
round(sum(case when day_open<=8 and goods_if_subbizcatname = 'cf' then count_num else null end)) as t01cczhaz,
round(sum(case when day_open<=8 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01cczhba,
round(sum(case when day_open<=8 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else null end)) as t01cczhbc,
round(sum(case when day_open<=8 and goods_if_subbizcatname ='sl' then count_num else null end)) as t01cczhbz,
round(sum(case when day_open<=8 and pay_result =0 and req_if_trademsg = 1 then count_num else null end)) as t01cczhza,
round(sum(case when day_open<=8 and pay_result =0 and req_if_trademsg = 2 then count_num else null end)) as t01cczhzb,
round(sum(case when day_open<=8 and pay_result =1 then count_num else null end)) as t01cczhzc,
round(sum(case when day_open<=8 then count_num else null end)) as t01cczhzz,
round(sum(case when day_pay<=1 and pay_result =1 then amt else 0 end)/sum(case when day_pay<=1 and pay_result =1 then count_num else 0 end), 2) as t01adazzc,
round(sum(case when day_pay<=1 then amt else 0 end)/sum(case when day_pay<=1 then count_num else 0 end), 2) as t01adazzz,
round(sum(case when day_pay<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adbzba,
round(sum(case when day_pay<=2 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when day_pay<=2 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adbzbc,
round(sum(case when day_pay<=2 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when day_pay<=2 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adbzbz,
round(sum(case when day_pay<=2 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=2 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adbzza,
round(sum(case when day_pay<=2 and pay_result =1 then amt else 0 end)/sum(case when day_pay<=2 and pay_result =1 then count_num else 0 end), 2) as t01adbzzc,
round(sum(case when day_pay<=2 then amt else 0 end)/sum(case when day_pay<=2 then count_num else 0 end), 2) as t01adbzzz,
round(sum(case when day_pay<=3 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when day_pay<=3 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adczaz,
round(sum(case when day_pay<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adczba,
round(sum(case when day_pay<=3 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when day_pay<=3 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adczbc,
round(sum(case when day_pay<=3 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when day_pay<=3 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adczbz,
round(sum(case when day_pay<=3 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=3 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adczza,
round(sum(case when day_pay<=3 and pay_result =1 then amt else 0 end)/sum(case when day_pay<=3 and pay_result =1 then count_num else 0 end), 2) as t01adczzc,
round(sum(case when day_pay<=3 then amt else 0 end)/sum(case when day_pay<=3 then count_num else 0 end), 2) as t01adczzz,
round(sum(case when day_pay<=4 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when day_pay<=4 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01addzac,
round(sum(case when day_pay<=4 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when day_pay<=4 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01addzaz,
round(sum(case when day_pay<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01addzba,
round(sum(case when day_pay<=4 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when day_pay<=4 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01addzbc,
round(sum(case when day_pay<=4 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when day_pay<=4 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01addzbz,
round(sum(case when day_pay<=4 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=4 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01addzza,
round(sum(case when day_pay<=4 and pay_result =1 then amt else 0 end)/sum(case when day_pay<=4 and pay_result =1 then count_num else 0 end), 2) as t01addzzc,
round(sum(case when day_pay<=4 then amt else 0 end)/sum(case when day_pay<=4 then count_num else 0 end), 2) as t01addzzz,
round(sum(case when day_pay<=5 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=5 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adezaa,
round(sum(case when day_pay<=5 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when day_pay<=5 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adezac,
round(sum(case when day_pay<=5 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when day_pay<=5 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adezaz,
round(sum(case when day_pay<=5 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=5 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adezba,
round(sum(case when day_pay<=5 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when day_pay<=5 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adezbc,
round(sum(case when day_pay<=5 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when day_pay<=5 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adezbz,
round(sum(case when day_pay<=5 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=5 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adezza,
round(sum(case when day_pay<=5 and pay_result =1 then amt else 0 end)/sum(case when day_pay<=5 and pay_result =1 then count_num else 0 end), 2) as t01adezzc,
round(sum(case when day_pay<=5 then amt else 0 end)/sum(case when day_pay<=5 then count_num else 0 end), 2) as t01adezzz,
round(sum(case when day_pay<=6 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=6 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adfzaa,
round(sum(case when day_pay<=6 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when day_pay<=6 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adfzac,
round(sum(case when day_pay<=6 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when day_pay<=6 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adfzaz,
round(sum(case when day_pay<=6 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=6 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adfzba,
round(sum(case when day_pay<=6 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when day_pay<=6 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adfzbc,
round(sum(case when day_pay<=6 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when day_pay<=6 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adfzbz,
round(sum(case when day_pay<=6 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=6 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adfzza,
round(sum(case when day_pay<=6 and pay_result =1 then amt else 0 end)/sum(case when day_pay<=6 and pay_result =1 then count_num else 0 end), 2) as t01adfzzc,
round(sum(case when day_pay<=6 then amt else 0 end)/sum(case when day_pay<=6 then count_num else 0 end), 2) as t01adfzzz,
round(sum(case when day_pay<=7 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=7 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adgzaa,
round(sum(case when day_pay<=7 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when day_pay<=7 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adgzac,
round(sum(case when day_pay<=7 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when day_pay<=7 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adgzaz,
round(sum(case when day_pay<=7 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=7 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adgzba,
round(sum(case when day_pay<=7 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when day_pay<=7 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adgzbc,
round(sum(case when day_pay<=7 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when day_pay<=7 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adgzbz,
round(sum(case when day_pay<=7 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=7 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adgzza,
round(sum(case when day_pay<=7 and pay_result =1 then amt else 0 end)/sum(case when day_pay<=7 and pay_result =1 then count_num else 0 end), 2) as t01adgzzc,
round(sum(case when day_pay<=7 then amt else 0 end)/sum(case when day_pay<=7 then count_num else 0 end), 2) as t01adgzzz,
round(sum(case when day_pay<=8 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=8 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adhzaa,
round(sum(case when day_pay<=8 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when day_pay<=8 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adhzac,
round(sum(case when day_pay<=8 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when day_pay<=8 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adhzaz,
round(sum(case when day_pay<=8 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=8 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adhzba,
round(sum(case when day_pay<=8 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when day_pay<=8 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adhzbc,
round(sum(case when day_pay<=8 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when day_pay<=8 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adhzbz,
round(sum(case when day_pay<=8 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_pay<=8 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adhzza,
round(sum(case when day_pay<=8 and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_pay<=8 and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adhzzb,
round(sum(case when day_pay<=8 and pay_result =1 then amt else 0 end)/sum(case when day_pay<=8 and pay_result =1 then count_num else 0 end), 2) as t01adhzzc,
round(sum(case when day_pay<=8 then amt else 0 end)/sum(case when day_pay<=8 then count_num else 0 end), 2) as t01adhzzz,
round(sum(case when row_num<=1 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when row_num<=1 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adizaa,
round(sum(case when row_num<=1 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when row_num<=1 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adizac,
round(sum(case when row_num<=1 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when row_num<=1 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adizaz,
round(sum(case when row_num<=1 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when row_num<=1 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adizba,
round(sum(case when row_num<=1 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when row_num<=1 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adizbc,
round(sum(case when row_num<=1 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when row_num<=1 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adizbz,
round(sum(case when row_num<=1 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when row_num<=1 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adizza,
round(sum(case when row_num<=1 and pay_result =1 then amt else 0 end)/sum(case when row_num<=1 and pay_result =1 then count_num else 0 end), 2) as t01adizzc,
round(sum(case when row_num<=1 then amt else 0 end)/sum(case when row_num<=1 then count_num else 0 end), 2) as t01adizzz,
round(sum(case when row_num<=2 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when row_num<=2 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adjzaa,
round(sum(case when row_num<=2 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when row_num<=2 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adjzac,
round(sum(case when row_num<=2 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when row_num<=2 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adjzaz,
round(sum(case when row_num<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when row_num<=2 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adjzba,
round(sum(case when row_num<=2 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when row_num<=2 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adjzbc,
round(sum(case when row_num<=2 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when row_num<=2 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adjzbz,
round(sum(case when row_num<=2 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when row_num<=2 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adjzza,
round(sum(case when row_num<=2 and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when row_num<=2 and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adjzzb,
round(sum(case when row_num<=2 and pay_result =1 then amt else 0 end)/sum(case when row_num<=2 and pay_result =1 then count_num else 0 end), 2) as t01adjzzc,
round(sum(case when row_num<=2 then amt else 0 end)/sum(case when row_num<=2 then count_num else 0 end), 2) as t01adjzzz,
round(sum(case when row_num<=3 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when row_num<=3 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adkzaa,
round(sum(case when row_num<=3 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when row_num<=3 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adkzac,
round(sum(case when row_num<=3 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when row_num<=3 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adkzaz,
round(sum(case when row_num<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when row_num<=3 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adkzba,
round(sum(case when row_num<=3 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when row_num<=3 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adkzbc,
round(sum(case when row_num<=3 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when row_num<=3 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adkzbz,
round(sum(case when row_num<=3 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when row_num<=3 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adkzza,
round(sum(case when row_num<=3 and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when row_num<=3 and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adkzzb,
round(sum(case when row_num<=3 and pay_result =1 then amt else 0 end)/sum(case when row_num<=3 and pay_result =1 then count_num else 0 end), 2) as t01adkzzc,
round(sum(case when row_num<=3 then amt else 0 end)/sum(case when row_num<=3 then count_num else 0 end), 2) as t01adkzzz,
round(sum(case when row_num<=4 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when row_num<=4 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adlzaa,
round(sum(case when row_num<=4 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when row_num<=4 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adlzac,
round(sum(case when row_num<=4 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when row_num<=4 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adlzaz,
round(sum(case when row_num<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when row_num<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adlzba,
round(sum(case when row_num<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when row_num<=4 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adlzbb,
round(sum(case when row_num<=4 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when row_num<=4 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adlzbc,
round(sum(case when row_num<=4 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when row_num<=4 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adlzbz,
round(sum(case when row_num<=4 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when row_num<=4 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adlzza,
round(sum(case when row_num<=4 and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when row_num<=4 and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adlzzb,
round(sum(case when row_num<=4 and pay_result =1 then amt else 0 end)/sum(case when row_num<=4 and pay_result =1 then count_num else 0 end), 2) as t01adlzzc,
round(sum(case when row_num<=4 then amt else 0 end)/sum(case when row_num<=4 then count_num else 0 end), 2) as t01adlzzz,
round(sum(case when goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzzaa,
round(sum(case when goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adzzac,
round(sum(case when goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adzzaz,
round(sum(case when goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzzba,
round(sum(case when goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adzzbb,
round(sum(case when goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adzzbc,
round(sum(case when goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adzzbz,
round(sum(case when pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzzza,
round(sum(case when pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adzzzb,
round(sum(case when pay_result =1 then amt else 0 end)/sum(case when pay_result =1 then count_num else 0 end), 2) as t01adzzzc,
round(sum(amt)/sum(count_num), 2) as t01adzzzz,
round(sum(case when day_open<=3 then amt else 0 end)/sum(case when day_open<=3 then count_num else 0 end), 2) as t01adzczz,
round(sum(case when day_open<=4 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when day_open<=4 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adzdbc,
round(sum(case when day_open<=4 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when day_open<=4 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adzdbz,
round(sum(case when day_open<=4 and pay_result =1 then amt else 0 end)/sum(case when day_open<=4 and pay_result =1 then count_num else 0 end), 2) as t01adzdzc,
round(sum(case when day_open<=4 then amt else 0 end)/sum(case when day_open<=4 then count_num else 0 end), 2) as t01adzdzz,
round(sum(case when day_open<=5 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when day_open<=5 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adzebc,
round(sum(case when day_open<=5 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when day_open<=5 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adzebz,
round(sum(case when day_open<=5 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=5 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzeza,
round(sum(case when day_open<=5 and pay_result =1 then amt else 0 end)/sum(case when day_open<=5 and pay_result =1 then count_num else 0 end), 2) as t01adzezc,
round(sum(case when day_open<=5 then amt else 0 end)/sum(case when day_open<=5 then count_num else 0 end), 2) as t01adzezz,
round(sum(case when day_open<=6 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when day_open<=6 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adzfac,
round(sum(case when day_open<=6 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when day_open<=6 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adzfaz,
round(sum(case when day_open<=6 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=6 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzfba,
round(sum(case when day_open<=6 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when day_open<=6 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adzfbc,
round(sum(case when day_open<=6 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when day_open<=6 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adzfbz,
round(sum(case when day_open<=6 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=6 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzfza,
round(sum(case when day_open<=6 and pay_result =1 then amt else 0 end)/sum(case when day_open<=6 and pay_result =1 then count_num else 0 end), 2) as t01adzfzc,
round(sum(case when day_open<=6 then amt else 0 end)/sum(case when day_open<=6 then count_num else 0 end), 2) as t01adzfzz,
round(sum(case when day_open<=7 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=7 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzgaa,
round(sum(case when day_open<=7 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when day_open<=7 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adzgac,
round(sum(case when day_open<=7 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when day_open<=7 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adzgaz,
round(sum(case when day_open<=7 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=7 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzgba,
round(sum(case when day_open<=7 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when day_open<=7 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adzgbc,
round(sum(case when day_open<=7 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when day_open<=7 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adzgbz,
round(sum(case when day_open<=7 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=7 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzgza,
round(sum(case when day_open<=7 and pay_result =1 then amt else 0 end)/sum(case when day_open<=7 and pay_result =1 then count_num else 0 end), 2) as t01adzgzc,
round(sum(case when day_open<=7 then amt else 0 end)/sum(case when day_open<=7 then count_num else 0 end), 2) as t01adzgzz,
round(sum(case when day_open<=8 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=8 and goods_if_subbizcatname = 'cf' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzhaa,
round(sum(case when day_open<=8 and goods_if_subbizcatname = 'cf' and pay_result =1 then amt else 0 end)/sum(case when day_open<=8 and goods_if_subbizcatname = 'cf' and pay_result =1 then count_num else 0 end), 2) as t01adzhac,
round(sum(case when day_open<=8 and goods_if_subbizcatname = 'cf' then amt else 0 end)/sum(case when day_open<=8 and goods_if_subbizcatname = 'cf' then count_num else 0 end), 2) as t01adzhaz,
round(sum(case when day_open<=8 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=8 and goods_if_subbizcatname ='sl' and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzhba,
round(sum(case when day_open<=8 and goods_if_subbizcatname ='sl' and pay_result =1 then amt else 0 end)/sum(case when day_open<=8 and goods_if_subbizcatname ='sl' and pay_result =1 then count_num else 0 end), 2) as t01adzhbc,
round(sum(case when day_open<=8 and goods_if_subbizcatname ='sl' then amt else 0 end)/sum(case when day_open<=8 and goods_if_subbizcatname ='sl' then count_num else 0 end), 2) as t01adzhbz,
round(sum(case when day_open<=8 and pay_result =0 and req_if_trademsg = 1 then amt else 0 end)/sum(case when day_open<=8 and pay_result =0 and req_if_trademsg = 1 then count_num else 0 end), 2) as t01adzhza,
round(sum(case when day_open<=8 and pay_result =0 and req_if_trademsg = 2 then amt else 0 end)/sum(case when day_open<=8 and pay_result =0 and req_if_trademsg = 2 then count_num else 0 end), 2) as t01adzhzb,
round(sum(case when day_open<=8 and pay_result =1 then amt else 0 end)/sum(case when day_open<=8 and pay_result =1 then count_num else 0 end), 2) as t01adzhzc,
round(sum(case when day_open<=8 then amt else 0 end)/sum(case when day_open<=8 then count_num else 0 end), 2) as t01adzhzz 

"""
